### ISSUE TITLE
Upgrade still broken?

### ISSUE THREAD

**Issue by fliiiix** [iocage/iocage#361] opened 2017-09-15 18:12 UTC
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [X] Supply `iocage --version`
```
Version 0.9.9.2 RC
```
- [X] Supply the commands used, along with any steps to recreate it.
```
sudo iocage upgrade -r 11.1-RELEASE ymir.l33t.network
```
- [X] Provide the output from the command you issued.
```
Looking up update.FreeBSD.org mirrors... 4 mirrors found.
Fetching metadata signature for 11.0-RELEASE from update5.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.

The following components of FreeBSD seem to be installed:
kernel/generic world/base world/doc world/lib32

The following components of FreeBSD do not seem to be installed:
kernel/generic-dbg src/src world/base-dbg world/lib32-dbg


Fetching metadata signature for 11.1-RELEASE from update5.freebsd.org... done.
Fetching metadata index... done.
Fetching 1 metadata patches. done.
Applying metadata patches... done.
Fetching 1 metadata files... done.
Inspecting system... done.
Fetching files from 11.0-RELEASE for merging... done.
Preparing to download files... done.
/tmp/tmp3biw6f8e: cannot open files/.gz: No such file or directory
/tmp/tmp3biw6f8e: cannot open files/.gz: No such file or directory
....truncated.....
/tmp/tmp3biw6f8e: cannot open files/.gz: No such file or directory
Attempting to automatically merge changes in files... done.

The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /boot/device.hints
Does this look reasonable (y/n)? 
```

Any Idea what I'm doing wrong or is this a real problem?

**Comment by skarekrow** [comment] 2017-09-15 18:13
That's totally normal :) missing files happen. If you hit y you're good. That's just how FreeBSD-update rolls.

**Comment by fliiiix** [comment] 2017-09-15 18:14
And the large number of 
```
/tmp/tmp3biw6f8e: cannot open files/.gz: No such file or directory
```

are also fine?

**Comment by fliiiix** [comment] 2017-09-15 18:20
Also I'm sure `/etc/crontab` is a file which is still needed 

```
The following file will be removed, as it no longer exists in
FreeBSD 11.1-RELEASE: /etc/crontab
Does this look reasonable (y/n)? y
```

**Comment by skarekrow** [comment] 2017-09-15 18:23
Yeah I don't think that should be removed. The gz stuff is normal. I'll look into this :)

**Comment by fliiiix** [comment] 2017-09-15 18:26
It looks like it tries to remove every file.

**Comment by skarekrow** [comment] 2017-09-20 23:08
I can't reproduce this :/ https://pastebin.com/x8cTBtwm Do you have a rough here's how I did this? Any additional information is helpful here, I pasted my whole thing in full above

**Comment by skarekrow** [comment] 2017-09-26 01:30
@fliiiix You didn't touch the configuration file inside the jail for freebsd-update did you? Can you paste those contents?

**Comment by fliiiix** [comment] 2017-09-27 16:35
Not with any intend but I will check and provide them.

**Comment by fliiiix** [comment] 2017-09-28 17:51
So sorry that this took for ever but I'm super busy at the moment. 

```
$ sudo find . -name freebsd-update 
./usr/sbin/freebsd-update
./var/db/freebsd-update
```

The first file looks fine: https://pastebin.com/Beq9Q430   
And the directory looks like this
``` 
$ sudo ls ./var/db/freebsd-update
55396a5778ba771feb16e769aea5764c21a19eff6ed9d1ef44de7aaf51b9f05a-rollback       install.sNTvb2
8cd61ec321d5a85031725ea4a0b7d91b98a7639bf692593cf3fc2783226c69de-rollback       install.t7STY1
d6452c7a48e205a71d7e83dedffcbcb6dea52d915ebbfafbfe13567aeda093dc-rollback       install.UcQObg
f465c3739385890c221dff1a05e578c6cae0d0430e46996d319db7439f884336-install        lasteolwarn
f9fe33c2b3a7b91615b474d4cf80a1f40b5dc3001feb9adcf7c0497b855d4f13-rollback       merge
files                                                                           pub.ssl
install.Atvmis                                                                  serverlist
install.BXznaY                                                                  serverlist_full
install.D8Ju1q                                                                  serverlist_tried
install.Ky201b                                                                  tag
install.n2qrOH                                                                  tINDEX.present
install.PKDXEE                                                                  tomerge-old
install.pnOY5n                                                                  tomerge-old-paths
```

The commands you provides are looking like the things I tried. So my two theory's right now are either it fails because my jails are somehow in a broken state or because they where create by a older version of iocage.

**Comment by skarekrow** [comment] 2017-10-06 01:19
Yeah freebsd-update is a tricky beast to figure out sometimes. @kmoore134 knows all about that :D

In the meantime, I'm going to close this as can't repro, but if you can please reply back and hopefully we can fix this.

**Comment by fliiiix** [comment] 2017-10-08 14:31
yeah I don't have the time to find a way to reproduce it so I just rebuild all my jails with 11.1 and I hope that the next upgrade goes smoother :/

**Comment by skarekrow** [comment] 2017-10-24 19:05
I *think* I know why this is happening. @fliiiix did you upgrade this jail once before this attempt?

**Closed as completed** 2017-10-24 19:48 UTC
Labels: bug

**Comment by fliiiix** [comment] 2017-10-26 18:34
no I didn't

**Comment by enalianya** [comment] 2017-11-22 17:38
This is also happening to me. And yes, I have before upgraded successfully from 10.3 to 11. I also tried upgrading earlier and freaked out in the middle when it started on the /tmp/bla. Any more insights?

**Comment by fengsi** [comment] 2017-12-14 22:41
Happened to me today, from 11.0-RELEASE jail to 11.1-RELEASE.  Host is 11.1-RELEASE.
All my jails were upgraded before, from legacy iocage.  They were all basejails, but now they seem to be simply jails.

**Comment by skarekrow** [comment] 2017-12-14 23:28
There hasn't been any release with this fix. Either install iocage from git or wait for a new iocage release :)

**Comment by fengsi** [comment] 2017-12-14 23:33
OK thanks - I'd probably wait for now.
Is there a way to put them back to basejail?  Or the entire concept is gone already. (sorry I didn't quite follow all the changes)

**Comment by skarekrow** [comment] 2017-12-14 23:58
Are you sure they were basejails? Because if they were, they should still be. Check `iocage get basejail JAIL` 

`list` wouldn't show this as technically it is just "jail" as far as the mechanism is concerned. That's the only way to confirm currently. 

If you want to recreate your jails, there is a new basejail concept available. You can create them by specifying `-b` to `create`.

**Comment by fengsi** [comment] 2017-12-15 00:32
You are right - yeah they are still basejail.  Guess I shouldn't have tried upgrade them then?  I know in docs it is mentioned only legacy iocage can do basejail upgrade.

**Comment by skarekrow** [comment] 2017-12-15 08:46
Nope :) Current iocage can do basejail upgrades but that's only available in github. The pkg version cannot currently, follow the advice I gave earlier and I hope your jail is OK.

**Comment by imp1sh** [comment] 2018-08-02 09:58
Can you please add an option that says "Yes, all and No, none" for the question if the file shall be removed.

It's really a pain in the axxxx to hit Y and Enter roughly 50-70 times.

**Comment by skarekrow** [comment] 2018-08-03 01:10
@imp1sh Create a separate issue if you could, with output of what you're describing. From memory, iocage should do this automatically as it's non-interactive upgrading by default.

**Comment by nbakker** [comment] 2019-10-02 11:10
In practice iocage doesn't do that automatically, unfortunately, and `yes | iocage upgrade -r …` doesn't work either.

I'm hitting this problem in roughly half my dozen jails. However, the problem seems to lie with `freebsd-update`.
