### ISSUE TITLE
iocage crashing kernel in head

### ISSUE THREAD

**Issue by colby-swandale** [iocage/iocage#298] opened 2015-12-22 22:39 UTC
Following our discussions from twitter [here](https://twitter.com/0xColby/status/6788634507396096000), the kernel is crashing when i attempt to start any jail in iocage.

I am running a compiled version of current that is less than 24 hours old. It should be noted that i have compiled the kernel with vnet enabled and have jails using the vnet subsystem. (i have also tried to start a jail without vnet with the same result.)

nothing is being dumped under `/var/crash` even though i have `dumpdev="AUTO"` set. But I do have an [image of what i am seeing on screen though](http://imgur.com/akQA4z6)

uname -a
`FreeBSD motoko 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r292546: Tue Dec 22 11:48:23 UTC 2015     colby@motoko:/usr/obj/usr/src/sys/ENHANCED  amd64`

Kernel Config:
```
root@motoko:/home/colby # cat /usr/src/sys/amd64/conf/ENHANCED
include GENERIC
nooptions       SCTP   # Stream Control Transmission Protocol
options         VIMAGE # VNET/Vimage support
options         RACCT  # Resource containers
options         RCTL   # same as above
```

I am not sure which steps to take now, so let me know what i can do to help.

**Comment by pr1ntf** [comment] 2015-12-22 22:44
Can you fix the image link? I think you are missing the image location and the end `)`. 

Thanks!

**Comment by colby-swandale** [comment] 2015-12-22 22:47
Fixed.

**Comment by skarekrow** [comment] 2015-12-22 22:49
Which iocage are you using? `Stable` or `Develop`? Either way that's odd. Your configuration for the kernel is the same as mine. I'm also on CURRENT. This should be reported upstream as it looks like VNET is causing the issues. Have you verified that world is up to date? By trying other utilities like `ps` or `sockstat`?

**Comment by colby-swandale** [comment] 2015-12-22 22:57
```
root@motoko:/home/colby # iocage --version
iocage 1.7.3 (2015/08/13)
```
I have followed the [handbook](https://www.freebsd.org/doc/handbook/makeworld.html) closely when i did a rebuild of kernel and world.

How would i verify that world is up to date? (sorry, i am just a casual user)

**Comment by skarekrow** [comment] 2015-12-23 22:01
I've always relied on just running `sockstat` or `ps` and looking for any weird errors they give. There may be a better way that somebody else has. But as it is, I cannot reproduce this :/

This seems to be some sort of problem with VNET on your machine. Outside of iocage's ballpark. I'd suggest using shared networking unless you absolutely need VNET.

Is this in a VM? I've seen this behavior in those. VNET is very crashy in that circumstance.

As is, I'm going to close this as "Can't reproduce". If other users have suggestions or I am able to reproduce it, I will reopen this ticket.

I suggest sending a bug report upstream (FreeBSD) with that picture attached and see if they have any ideas.

Good luck!

**Closed** 2015-12-23 22:02 UTC
Labels: bug, can't reproduce

**Comment by colby-swandale** [comment] 2015-12-26 10:29
Hey guys, i just updated to the latest commit and rebuilt world/kernel and everything appears to be working now. Thanks.

**Comment by skarekrow** [comment] 2015-12-30 07:13
Ah that's great to hear!
