### ISSUE TITLE
iocage create error 'no such file or directory'

### ISSUE THREAD

**Issue by tbswork1** [iocage/iocage#1290] opened 2022-12-02 10:41 UTC
Make sure to follow and check these boxes before submitting an issue! Thank you.

- version 1.2
- `sudo iocage create -r LATEST -n mycage`

out put 
```
FileNotFoundError: [Errno 2] No such file or directory: '/zroot/iocage/releases/13.1</p-RELEASE/root/bin/freebsd-version'
```
After numerous tries with same command , I bypassed the connection errors and ended up with the one above. I have no idea how it got the path `/zroot/iocage/releases/13.1</p-RELEASE/root/bin/freebsd-version'`, this one exists though:
 `/zroot/iocage/releases/13.1-RELEASE/root/`

**Comment by germel** [comment] 2022-12-26 22:01
The problem is caused by this line:
`                 rel = rel[1].strip('</td').strip("releng/")`
in line 682 of `/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py`, which expects only a `</td` tag after the release number. In reality the closing tag may also be `</p` or `</code`.  It should be changed to:
`                 rel = rel[1].strip('</td').strip('</p').strip('</code').strip("releng/")`

You can edit the file to fix it or apply the attached patch. If you save it in /tmp, you can apply it by running as root the following command:
`patch /usr/local/lib/python3.7/site-packages/iocage_lib/ioc_common.py < /tmp/ioc_common.txt`

[ioc_common.txt](https://github.com/iocage/iocage/files/10304925/ioc_common.txt)

**Comment by espen-j** [comment] 2023-12-04 18:10
Still an issue, and the patch above still fixes it 👍

**Closed as completed** 2024-04-04 18:35 UTC
