### ISSUE TITLE
rcshutdown produces errors, fails to stop jails

### ISSUE THREAD

**Issue by freqlabs** [iocage/iocage#105] opened 2015-06-09 00:36 UTC
To test that all my jails are starting in the correct order, I tried running `iocage rcshutdown` to stop all the jails with the "boot" property set to "on", after which I intended to run `iocage rcboot` to start them again. The rcshutdown command only stopped one of the jails, and I received the following errors:
```
* [I|O|C] shutting down jails...
* Stopping 9ea25ab3-0db2-11e5-b42b-0025907cc3f4 (some.jail.name)
  + Running pre-stop         OK
  + Stopping services        OK
  + Removing jail process    OK
  + Running post-stop        OK
cannot open 'system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4
system/iocage/jails/879b0704-0d70-11e5-b42b-0025907cc3f4
system/iocage/jails/9e553f4d-0d55-11e5-b42b-0025907cc3f4
system/iocage/jails/9ea25ab3-0db2-11e5-b42b-0025907cc3f4
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4': invalid dataset name
[: ==: unexpected operator
cannot open 'system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4
system/iocage/jails/879b0704-0d70-11e5-b42b-0025907cc3f4
system/iocage/jails/9e553f4d-0d55-11e5-b42b-0025907cc3f4
system/iocage/jails/9ea25ab3-0db2-11e5-b42b-0025907cc3f4
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4': invalid dataset name
[: ==: unexpected operator
cannot open 'system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4
system/iocage/jails/879b0704-0d70-11e5-b42b-0025907cc3f4
system/iocage/jails/9e553f4d-0d55-11e5-b42b-0025907cc3f4
system/iocage/jails/9ea25ab3-0db2-11e5-b42b-0025907cc3f4
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4': invalid dataset name
[: ==: unexpected operator
cannot open 'system/iocage/jails/2c9a5625-0ce9-11e5-b42b-0025907cc3f4
system/iocage/jails/879b0704-0d70-11e5-b42b-0025907cc3f4
system/iocage/jails/9e553f4d-0d55-11e5-b42b-0025907cc3f4
system/iocage/jails/9ea25ab3-0db2-11e5-b42b-0025907cc3f4
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4': invalid dataset name
[: ==: unexpected operator
```
If this is to be expected when not performing an actual shutdown of the host, a simple note added to the documentation explaining that the commands should not be invoked by a user might suffice.

**Comment by pannon** [comment] 2015-06-09 17:23
@freqlabs I have tested this and could not reproduce. Please if possible, could you destroy those jails and re-create them? To me it looks like those jails are not fully initialized.

Also are these clones or basejails? Would be good if you could post the output of `iocage get all UUID` for one of those affected jails and `zfs list -r system/iocage/jails/UUID`

**Comment by freqlabs** [comment] 2015-06-09 21:41
These are all basejails. When I get the chance I'll try reproducing this behavior on a machine I'm not using. Here is some additional info for you:

```
# iocage show priority | sort -nk 2
UUID                                  priority
9e553f4d-0d55-11e5-b42b-0025907cc3f4  5
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  10
879b0704-0d70-11e5-b42b-0025907cc3f4  10
a092e40b-0cbc-11e5-b42b-0025907cc3f4  10
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  20
```

The next jail to be shut down should be `a092e40b-0cbc-11e5-b42b-0025907cc3f4`, so more info on that one:
```
# iocage get all a092e40b-0cbc-11e5-b42b-0025907cc3f4
interfaces:vnet0:bridge0,vnet1:bridge1
vnet:off
host_hostname:a092e40b-0cbc-11e5-b42b-0025907cc3f4
hostname:a092e40b-0cbc-11e5-b42b-0025907cc3f4
ip4_addr:em0|999.999.999.999,lo1|127.0.1.100
ip4_saddrsel:1
ip4:new
ip6_addr:none
ip6_saddrsel:1
ip6:new
defaultrouter:none
defaultrouter6:none
exec_fib:0
vnet0_mac:none
vnet1_mac:none
vnet2_mac:none
vnet3_mac:none
devfs_ruleset:4
mount_devfs:1
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_poststop:/usr/bin/true
exec_poststart:/usr/bin/true
exec_clean:1
exec_timeout:60
stop_timeout:30
exec_jail_user:root
exec_system_jail_user:0
exec_system_user:root
mount_fdescfs:1
mount_procfs:0
enforce_statfs:2
children_max:0
login_flags:-f root
securelevel:2
allow_set_hostname:0
allow_sysvipc:0
allow_raw_sockets:0
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_socket_af:0
host_hostuuid:a092e40b-0cbc-11e5-b42b-0025907cc3f4
memoryuse:8G:log
memorylocked:off
vmemoryuse:off
maxproc:off
cputime:off
pcpu:off
datasize:off
stacksize:off
coredumpsize:off
openfiles:off
pseudoterminals:off
swapuse:off
nthr:off
msgqqueued:off
msgqsize:off
nmsgq:off
nsemop:off
nshm:off
shmsize:off
wallclock:off
tag:www.example.com
template:no
rlimits:off
boot:on
notes:none
owner:root
priority:10
last_started:2015-06-09_20:47:02
type:basejail
hostid:49434d53-0200-907c-2500-7c902500f4c3
cpuset:off
jail_zfs:off
jail_zfs_dataset:somedataset
release:10.1-RELEASE
hack88:0
sync_stat:-
sync_target:none
sync_tgt_zpool:none
```

```
# zfs list -r system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4
NAME                                                                        USED  AVAIL  REFER  MOUNTPOINT
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4                    159M  1.72T   100K  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root               159M  1.72T   131M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/bin            72K  1.72T   960K  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/bin
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/boot            8K  1.72T  1.26M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/boot
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/lib            72K  1.72T  5.54M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/lib
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/libexec         8K  1.72T   260K  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/libexec
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/rescue          8K  1.72T  4.95M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/rescue
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/sbin           72K  1.72T  3.86M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/sbin
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr          28.0M  1.72T  27.5M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/bin       120K  1.72T  49.4M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/bin
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/include     8K  1.72T  11.4M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/include
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/lib       136K  1.72T  41.2M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/lib
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/lib32       8K  1.72T  40.2M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/lib32
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/libdata     8K  1.72T   180K  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/libdata
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/libexec    72K  1.72T  2.22M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/libexec
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/sbin       72K  1.72T  8.04M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/sbin
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/share      72K  1.72T  45.8M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/share
system/iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/src         8K  1.72T   506M  /iocage/jails/a092e40b-0cbc-11e5-b42b-0025907cc3f4/root/usr/src
```

And for fun some more info:
```
# iocage show jail_zfs
UUID                                  jail_zfs
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  off
879b0704-0d70-11e5-b42b-0025907cc3f4  off
9e553f4d-0d55-11e5-b42b-0025907cc3f4  on
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  on
a092e40b-0cbc-11e5-b42b-0025907cc3f4  off
# iocage show jail_zfs_dataset
UUID                                  jail_zfs_dataset
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  somedataset
879b0704-0d70-11e5-b42b-0025907cc3f4  somedataset
9e553f4d-0d55-11e5-b42b-0025907cc3f4  somedataset/database
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  somedataset/mail
a092e40b-0cbc-11e5-b42b-0025907cc3f4  somedataset
# iocage show allow_mount
UUID                                  allow_mount
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  0
879b0704-0d70-11e5-b42b-0025907cc3f4  0
9e553f4d-0d55-11e5-b42b-0025907cc3f4  1
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  1
a092e40b-0cbc-11e5-b42b-0025907cc3f4  0
# iocage show allow_mount_zfs
UUID                                  allow_mount_zfs
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  0
879b0704-0d70-11e5-b42b-0025907cc3f4  0
9e553f4d-0d55-11e5-b42b-0025907cc3f4  1
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  1
a092e40b-0cbc-11e5-b42b-0025907cc3f4  0
# iocage show enforce_statfs
UUID                                  enforce_statfs
2c9a5625-0ce9-11e5-b42b-0025907cc3f4  2
879b0704-0d70-11e5-b42b-0025907cc3f4  2
9e553f4d-0d55-11e5-b42b-0025907cc3f4  1
9ea25ab3-0db2-11e5-b42b-0025907cc3f4  1
a092e40b-0cbc-11e5-b42b-0025907cc3f4  2
```

**Comment by pannon** [comment] 2015-06-10 16:06
@freqlabs I think this issue might be related to `somedataset` . Could you try to reset those jails and check whether the jail_zfs_dataset is set to default? Then retest the `rcshutdown` action?

**Comment by freqlabs** [comment] 2015-06-10 17:06
```
# zfs get -r jailed system/iocage/jails | grep on
system/iocage/jails/879b0704-0d70-11e5-b42b-0025907cc3f4/root/data         jailed    on      local
system/iocage/jails/9e553f4d-0d55-11e5-b42b-0025907cc3f4/root/data         jailed    on      local
system/iocage/jails/9ea25ab3-0db2-11e5-b42b-0025907cc3f4/root/data         jailed    on      local
```

I wonder why these datasets would be jailed? Three is an odd number to have here.

**Comment by freqlabs** [comment] 2015-06-11 20:41
I did a full reset of those jails, and rcshutdown seemed to work fine. Just changing the `jail_zfs_dataset` property back to the default value did not fix the problem. I have noticed now that each time I run rcshutdown, the first jail still running is sucessfully shut down, but all following jails fail in the above manner. What appears to be happening is that `$i` in the for loop is losing its comma somehow, so instead of `${priority},${uuid}` its value is `$priority $uuid`, causing the call to `cut` to not properly separate the UUID from the priority. I'm having a heck of a time figuring out what is causing this, however.

**Comment by pannon** [comment] 2015-06-12 12:59
Closing as we could not reproduce this in our environment.

**Closed by pannon** 2015-06-12 12:59 UTC
Labels: bug

**Comment by freqlabs** [comment] 2015-06-12 14:44
This can be reproduced by setting `ip4_addr` to anything and having more than one jail. Only occurs when `vnet` is not on.

The problem lies in `__stop_legacy_networking`. This function sets IFS=',' but since IFS was not restricted to local scope and is not reset at the end of the function, it affects the rest of the script's execution following the first call to this function.

I will submit a PR that sprinkles the cure into this function.
