### ISSUE TITLE
IPv6 is not usable

### ISSUE THREAD

**Issue by MarkMartinec** [iocage/iocage#305] opened 2016-01-04 19:00 UTC
jail(8) allows to specify extra ifconfig parameters with ip4.addr and ip6.addr:

> ip4.addr
>   In addition to the IP addresses that are passed to the kernel, an
>   interface, netmask and additional paramters (as supported by
>   ifconfig(8)) may also be specified, in the form
>   “interface|ip-address/netmask param ...”. [...]

which makes it possible to specify options like vhid for CARPed addresses.

It seems it is not possible to do so trough iocage (version 1.7.3, FreeBSD 10.2),
as it leaves out extra parameters from a quoted string, producing a syntax error
thrown by jail(8).

For example, given a setting:
```
iocage set ip4_addr='DEFAULT|10.0.0.246 vhid 23 advskew 100' xxx
iocage set ip6_addr='DEFAULT|2001:db8::246 vhid 23 advskew 100' xxx
```
the iocage start calls jail(8) as follows:

```
$ jail -c 'ip4.addr=igb0|10.0.0.246' vhid 23 advskew 100 ip4.saddrsel=1 ip4=new 'ip6.addr=igb0|2001:db8::246' vhid 23 advskew 100 ip6.saddrsel=1 ip6=new ...
jail: unknown parameter: vhid
jail: unknown parameter: 23
jail: unknown parameter: advskew
jail: unknown parameter: 100
```
Note that the:
>  'ip4.addr=igb0|10.0.0.246' vhid 23 advskew 100
>  'ip6.addr=igb0|2001:db8::246' vhid 23 advskew 100

should have been quoted like:
>  ip4.addr='igb0|10.0.0.246 vhid 23 advskew 100'
>  ip6.addr='igb0|2001:db8::246 vhid 23 advskew 100'

**Comment by skarekrow** [comment] 2016-01-04 20:45
Does this issue also occur for you if you double quote the initial set?

`"iocage set ip4_addr='DEFAULT|10.0.0.246 vhid 23 advskew 100' xxx"`

Will try to reproduce a bit later.

**Comment by MarkMartinec** [comment] 2016-01-04 23:13
Note that the zfs property seems to get set correctly, it's just that the 'iocage start'
messes things up:
```
# zfs get org.freebsd.iocage:ip4_addr yyy/iocage/jails/e795...f3a
yyy/iocage/jails/e795...f3a  org.freebsd.iocage:ip4_addr  DEFAULT|10.0.0.246 vhid 23 advskew 100  local
```

Tried the following:
> $ iocage set 'ip4_addr="DEFAULT|10.0.0.246 vhid 23 advskew 100"' xxx

and the quoting came out even weirder (as reported by sh -x iocage start xxx):
> jail -c 'ip4.addr="igb0|10.0.0.246' vhid 23 advskew '100"' ip4.saddrsel=1 [...]

The other way around was diferent but no better:
> $ iocage set "ip4_addr='DEFAULT|10.0.0.246 vhid 23 advskew 100'" xxx
>  jail -c 'ip4.addr='\''igb0|10.0.0.246' vhid 23 advskew '100'\' ip4.saddrsel=1 [...]

**Comment by skarekrow** [comment] 2016-01-06 03:26
Interesting, thanks for the great feedback. Currently moving things to a different basejail setup, and will try to fix this bug along with that.

**Comment by skarekrow** [comment] 2016-01-06 06:50
I actually cannot reproduce this error.

Here's what `jail` shows me with my debug:
```
jail -c 'ip4.addr=vtnet0|192.168.1.75 vhid 23 advskew 100' ip4.saddrsel=1 ip4=new ip6.addr= ip6.saddrsel=1 ip6=new name=ioc-669ba589-b425-11e5-86ca-00a098690e88 host.domainname=none host.hostname=669ba589-b425-11e5-86ca-00a098690e88 path=/iocage/jails/669ba589-b425-11e5-86ca-00a098690e88/root securelevel=2 host.hostuuid=669ba589-b425-11e5-86ca-00a098690e88 devfs_ruleset=4 enforce_statfs=2 children.max=0 allow.set_hostname=1 allow.sysvipc=0 allow.raw_sockets=0 allow.chflags=0 allow.mount=0 allow.mount.devfs=0 allow.mount.nullfs=0 allow.mount.procfs=0 allow.mount.tmpfs=0 allow.mount.zfs=0 allow.quotas=0 allow.socket_af=0 exec.prestart=/usr/bin/true exec.poststart=/usr/bin/true exec.prestop=/usr/bin/true 'exec.stop=/bin/sh /etc/rc.shutdown' exec.clean=1 exec.timeout=60 exec.fib=0 stop.timeout=30 mount.fstab=/iocage/jails/669ba589-b425-11e5-86ca-00a098690e88/fstab mount.devfs=1 mount.fdescfs=1 allow.dying exec.consolelog=/iocage/log/-console.log persist
```

```
bschneider@iocage-dev:~ % iocage get ip4_addr iptest
DEFAULT|192.168.1.75 vhid 23 advskew 100
```

```
bschneider@iocage-dev:~ % ifconfig
vtnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=80028<VLAN_MTU,JUMBO_MTU,LINKSTATE>
	ether 00:a0:98:69:0e:88
	inet 192.168.1.249 netmask 0xffffff00 broadcast 192.168.1.255
	inet 192.168.1.75 netmask 0xffffffff broadcast 192.168.1.75 vhid 23
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
	carp: MASTER vhid 23 advbase 1 advskew 100
```

This is on the `develop` branch. So you may want to switch to that if you need this fixed in the meantime.

**Comment by MarkMartinec** [comment] 2016-01-06 13:46
Tried it now with sysutils/iocage-devel (2015-12-07). Indeed the ip4.addr is now
passed correctly at a jail start. But for some reason the ip6.addr is now left blank:

> $ iocage set ip6_addr='DEFAULT|2001:db8::246 vhid 23 advskew 100' xxx
>
> jail -c 'ip4.addr=igb0|10.0.0.246 vhid 23 advskew 100' ip4.saddrsel=1 ip4=new ip6.addr= ip6.saddrsel=1 ip6=new

The problem at 'iocage stop' remains however:

```
# iocage stop xxx
* Stopping e795fefa-a4df-11e5-8958-00259026bf3a (xxx)
  + Running pre-stop         OK
  + Stopping services        OK
[: igb0|10.0.0.246: unexpected operator
[: igb0|2001:db8::246: unexpected operator
  + Removing jail process    OK
  + Running post-stop        OK
```
Or with a sh -x debugging:

```
+ echo 'DEFAULT|10.0.0.246' vhid 23 advskew 100
+ sed 's/DEFAULT|/igb0|/g'
+ ip4_addr='igb0|10.0.0.246 vhid 23 advskew 100'
+ echo 'DEFAULT|2001:db8::246' vhid 23 advskew 100
+ sed 's/DEFAULT|/igb0|/g'
+ ip6_addr='igb0|2001:db8::246 vhid 23 advskew 100'
+ [ 'igb0|10.0.0.246' vhid 23 advskew 100 != none ]
[: igb0|10.0.0.246: unexpected operator
+ [ 'igb0|2001:db8::246' vhid 23 advskew 100 != none ]
[: igb0|2001:db8::246: unexpected operator
```

**Comment by MarkMartinec** [comment] 2016-01-06 18:18
> But for some reason the ip6.addr is now left blank

It's worse: the sysutils/iocage-devel can't provide IPv6-only jails with their IP address.
I have to downgrade to sysutils/iocage.

**Comment by skarekrow** [comment] 2016-01-06 22:46
What do you mean it can't provide IPv6-only jails with their IP address? Is it acting differently then just being blank?

**Comment by MarkMartinec** [comment] 2016-01-06 23:21
As reported in the example above, the "ip6.addr=" parameter to jail(8) is empty,
despite the parameter being configured. This is specific to sysutils/iocage-devel,
it works normally with sysutils/iocage (from ports).

> jail -c 'ip4.addr=igb0|10.0.0.246 vhid 23 advskew 100' ip4.saddrsel=1
>   ip4=new ip6.addr= ip6.saddrsel=1 ip6=new

In other words, the same jail (configured with both ipv4 and ipv6 address)
starts up normally with sysutils/iocage and the interface receives both addresses,
but when started with sysutils/iocage-devel it only receives an IPv4 address
but no IPv6 address.

This is unrelated to the originally reported problem, changing the subject is confusing.
It is also unrelated to the presence or absence of additional ifconfig parameters.

**Comment by skarekrow** [comment] 2016-01-06 23:23
Yep I've fixed the bug, just testing currently. As for changing the subject, I did that instead of asking you to open a new issue when this is one I was able to reproduce. Leaving the old title and the "cannot reproduce" label doesn't serve a purpose if an actual bug was reported here. I don't know why you're telling me it's unrelated to additional ifconfig parameters as that's no longer in the title ;)

**Closed** 2016-01-07 00:34 UTC
Labels: bug

**Comment by MarkMartinec** [comment] 2016-01-07 13:42
Thank you! I have install the develop branch from git, and this all works now correctly.

I hope this fix eventually trickles down to the master branch and to ports collection.
( Btw, still need the FreeBSD folks to fix the jail(8) utility: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205926 )
