### ISSUE TITLE
12.0-Release jails not working

### ISSUE THREAD

**Issue by SawFishDaemon** [iocage/iocage#885] opened 2019-03-01 23:53 UTC
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version`
- [ ] Supply the commands used, along with any steps to recreate it.
- [ ] Provide the output from the command you issued.
- [ ] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

SawFish@trident-1767] ~% iocage --version
Version 1.0 ALPHA

[SawFish@trident-1767] ~% sudo iocage fetch
Password:
********************************************************************************
fdescfs(5) is not mounted, performance may suffer. Please run:
mount -t fdescfs null /dev/fd
You can also permanently mount it in /etc/fstab with the following entry:
fdescfs /dev/fd  fdescfs  rw  0  0
********************************************************************************

[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE (EOL)
[4] 10.4-RELEASE (EOL)
[5] 11.0-RELEASE (EOL)
[6] 11.1-RELEASE (EOL)
[7] 11.2-RELEASE
[8] 12.0-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (Not a RELEASE)
Type EXIT to quit: 8
Fetching: 12.0-RELEASE

Extracting: base.txz... 
Extracting: lib32.txz... 
doc.txz missing, will try to redownload!
src.txz missing, will try to redownload!
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 170, in cli
    ioc.IOCage(exit_on_error=True).fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 992, in fetch
    silent=self.silent, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 250, in fetch_release
    rel = self.fetch_http_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 535, in fetch_http_release
    self.fetch_download(missing, missing=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 744, in fetch_download
    r.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://download.freebsd.org/ftp/releases/amd64/12.0-RELEASE/doc.txz

I tried to open a bug report on bugs.freebsd.org about the last (404) error, but someone had already opened it... bug number 234313 (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=234313)

I can make jails with any other RELEASE but not 12.0-RELEASE

**Comment by skarekrow** [comment] 2019-03-04 17:42
Dupe of https://github.com/iocage/iocage/issues/761

**Closed as completed by skarekrow** 2019-03-04 17:42 UTC
Labels: duplicate

**Comment by skarekrow** [comment] 2019-03-04 19:13
Oops forgot to include in my comment @SawFishDaemon, upgrading iocage to 1.0-RELEASE or later(I recommend the latter ;)) will solve this for you, if you cannot or don't want to do that, manually specifying the files to fetch should resolve this as well.
