### ISSUE TITLE
Jails created with earlier version error on manipulation using 0.9.9.1

### ISSUE THREAD

**Issue by VulcanRidr** [iocage/iocage#369] opened 2017-09-21 22:47 UTC
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [ ] Supply `iocage --version` 0.9.9.1 08/01/2017 on TrueOS 12,0 CURRENT

Command used was 

`# iocage start 542de48b-312d-4750-b089-47be58325803`
Note that this was on an existing machine created with an earlier version (perhaps py27-iocage-0.9.9?) on trueOS

Output of the command:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/start.py", line 55, in cli
    ioc.IOCage(jail, rc=rc).start()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1100, in start
    conf = ioc_json.IOCJson(path, silent=self.silent).json_load()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 178, in json_load
    if jail_dataset.mountpoint is None:
  File "libzfs.pyx", line 2283, in libzfs.ZFSDataset.mountpoint.__get__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 65: ordinal not in range(128)

Expected behavior -> starting of the jail.

Note that attempted deletion of the older jail (using `iocage destroy 542de48b-312d-4750-b089-47be58325803` gave the same error as above. Since I was able to successfully create a jail, can I simply rm -rf /iocage/jails/542de48b-312d-4750-b089-47be58325803, or is there other cruft that needs to be cleaned up as well?

**Comment by skarekrow** [comment] 2017-09-21 23:06
This is a duplicate of a ticket here. I pinged @kmoore134 and he readded the patch that fixes this to trueos. So whenever those packages come you will be good to go

**Closed as completed by skarekrow** 2017-09-21 23:06 UTC
Labels: duplicate
