### ISSUE TITLE
"iocage create" fails with non-sense error when creating jail with existing name

### ISSUE THREAD

**Issue by abelbabel** [iocage/iocage#439] opened 2017-12-05 10:47 UTC
Hi,

with iocage 0.9.9.2 09/30/2017 the following might happen:

```
# iocage create -n test -t template
test successfully created!
# iocage create -n test -t template
Template: template not found!
Created Templates:
  template
```

The error message should be different; like: "jail test already exists" ...

Regards,
abelbabel

**Comment by skarekrow** [comment] 2017-12-05 20:41
Duplicate of https://github.com/iocage/iocage/issues/414

Please search :)

**Closed as completed by skarekrow** 2017-12-05 20:41 UTC
Labels: duplicate

**Comment by abelbabel** [comment] 2017-12-05 23:04
Sorry for the duplicates!
