### ISSUE TITLE
Cloning from snapshot does not work: Jail not found

### ISSUE THREAD

**Issue by utrenkner** [iocage/iocage#546] opened 2018-05-08 12:52 UTC
I was trying to clone a jail from an existing snapshot, following the [documentation](https://iocage.readthedocs.io/en/latest/advanced-use.html#clones). But iocage tells me it could not find the original jail. Therefore, I made another snapshot with icoage and tried to clone from there - again, iocage does not find the jail:
```
% sudo iocage snapshot web2
Snapshot: zroot/iocage/jails/web2@2018-05-08_12:39:09 created.
sudo iocage clone web2@2018-05-08_12:39:09 --name web2a
jail 'web2@2018-05-08_12:39:09' not found!
```
Could this be related to #505 ? Maybe iocage cannot read the list of snapshots and therefore answers that it cannot find it.
Cloning directly from the jail web2 worked without a problem.

* iocage Version 0.9.10 2017/12/22
* HardenedBSD 11.2-PRERELEASE (userland and kernel at 1101515)

**Comment by skarekrow** [comment] 2018-05-08 19:33
Dupe of #520

**Closed as completed by skarekrow** 2018-05-08 19:33 UTC
Labels: duplicate
