### ISSUE TITLE
Error on migrate: UnboundLocalError: local variable 'uuid' referenced before assignment

### ISSUE THREAD

**Issue by lukaszczerpak** [iocage/iocage#35] opened 2017-02-18 19:21 UTC
I tried to migrate to python based version and got the following error. Please let me know if what kind of extra information would be needed or how to track it down.

iocage version 0.9.4
OS: 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11

root@xyz ~ _ iocage migrate
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.4', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/migrate.py", line 28, in migrate_cmd
    jails, paths = IOCList("uuid").get_datasets()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 67, in get_datasets
    conf = IOCJson(jail).load_json()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_json.py", line 107, in load_json
    self.convert_to_json_zfs(uuid)
UnboundLocalError: local variable 'uuid' referenced before assignment

**Comment by skarekrow** [comment] 2017-02-18 19:23
Can you provide a `iocage list` from the old iocage please?

**Comment by lukaszczerpak** [comment] 2017-02-18 19:25
Thanks! Still on old iocage as the new one failed and doesn't work:

```
JID   UUID                                  BOOT  STATE  TAG                   IP
21    34f25ce3-7ff0-11e6-952f-003048f8f8e6  on    up     xxx   192.168.x.y
24    762a413b-d4f2-11e5-b13a-003048f8f8e6  on    up     xxx    192.168.x.y
23    7b43467a-d4f2-11e5-b13a-003048f8f8e6  on    up     xxx   192.168.x.y
22    7fde4ec2-d4f2-11e5-b13a-003048f8f8e6  on    up     xxx   192.168.x.y
20    a07a28ae-d4f1-11e5-b13a-003048f8f8e6  on    up     xxx     192.168.x.y
```

Update:

```
root@xyz /iocage/jails » ls -1
34f25ce3-7ff0-11e6-952f-003048f8f8e6
762a413b
7b43467a
7fde4ec2
a07a28ae-d4f1-11e5-b13a-003048f8f8e6
```

**Comment by skarekrow** [comment] 2017-02-18 19:26
Yes, the new one will require you to transition before you could use `list`.

What version of the old `iocage` are you using?

**Comment by lukaszczerpak** [comment] 2017-02-18 19:26
iocage 1.7.4 (2016/02/17)

**Comment by skarekrow** [comment] 2017-02-18 19:27
Then you don't need migrate, it's only for the `develop` branch of the old iocage. You can just issue `iocage COMMAND` as root with the new one and you will be good to go :)

**Comment by lukaszczerpak** [comment] 2017-02-18 19:28
the new one throws same error on `list` command - I hoped to get it working without migration but it failed:

```
root@xyz ~ _ iocage list
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.4', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python2.7/site-packages/iocage/main.py", line 92, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/iocage/cli/list.py", line 24, in list_cmd
    IOCList(dataset_type, header, _long).get_datasets()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 60, in get_datasets
    self.list_all(datasets)
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_list.py", line 118, in list_all
    conf = IOCJson(jail).load_json()
  File "/usr/local/lib/python2.7/site-packages/iocage/lib/ioc_json.py", line 107, in load_json
    self.convert_to_json_zfs(uuid)
UnboundLocalError: local variable 'uuid' referenced before assignment
```

**Comment by skarekrow** [comment] 2017-02-18 19:29
Interesting, something must have gone wrong, let me get an environment setup quick and fix this.

**Comment by skarekrow** [comment] 2017-02-18 19:29
You aren't using `hack88` are you?

**Comment by lukaszczerpak** [comment] 2017-02-18 19:31
it's my production server but can experiment if needed.

Hack88 is used on 3 jails, the remaining 2 have it disabled.

**Comment by skarekrow** [comment] 2017-02-18 19:31
Alright, thanks for the information. This shouldn't need your experimentation, so no worries. The error is clear, the why is confusing me. We'll have this solved soon 👍

**Comment by skarekrow** [comment] 2017-02-18 20:10
So the issue is `hack88`. I have a fix, but working on a nice migration for the user so you guys don't have to do anything manual. Won't be long now!

**Comment by skarekrow** [comment] 2017-02-18 21:29
Ok @lukaszczerpak, all fixed :)

Thanks for reporting this.

For you to use this do the following:

1. Remove the old iocage
2. `pkg install python3`
3. `python3 -m ensurepip`
4. `git clone https://github.com/iocage/iocage`
5. `pip3 install ./iocage`
6. Profit

This will stop all your jails, so if you need them up for anything mission critical, I suggest holding off until you have some time.

**Comment by lukaszczerpak** [comment] 2017-02-19 09:03
Thanks, it's better but still have some issues, two in particular. Not sure whether to track it here or move to a new issue though.

After installing iocage 0.9.6 and running `iocage list` it started converting jails to the new format but stopped in the middle and thrown error as follows:

```
» iocage list
hack88 is no longer supported.
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6 is being converted to zroot/iocage/jails/762a413b permanently.
cannot rename 'zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6': child dataset with inherited mountpoint is used in a non-global zone
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_json.py", line 111, in json_load
    with open(self.location + "/config.json", "r") as conf:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/762a413b/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.5/site-packages/iocage/main.py", line 97, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/iocage/cli/list.py", line 45, in list_cmd
    IOCList(dataset_type, header, _long).list_datasets()
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_list.py", line 60, in list_datasets
    self.list_all(datasets)
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_list.py", line 120, in list_all
    conf = IOCJson(jail).json_load()
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_json.py", line 182, in json_load
    short_dataset])
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_common.py", line 191, in checkoutput
    out = check_output(*args, **kwargs).decode("utf-8")
  File "/usr/local/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['zfs', 'rename', '-f', 'zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6', 'zroot/iocage/jails/762a413b']' returned non-zero exit status 1
```

That happened 2 or 3 times - I got an impression that `hack88` caused this as iocage tried to use full UUID path whereas it was short UUID on filesystem. Eventually, all jails got `config.json` created, but none got renamed to full UUID. At the end I was able to run them without any further issues.

I think `zfs rename` didn't succeed and thus the command didn't convert zfs paths to be based on full UUID. As a consequence of this, some further commands failed - here are details (not creating a new issue as it's highly related to this thread in my opinion):

```
» iocage update www

* Updating 762a413b-d4f2-11e5-b13a-003048f8f8e6 (www) to the latest patch level...
mount: /iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 11, in <module>
    load_entry_point('iocage==0.9.6', 'console_scripts', 'iocage')()
  File "/usr/local/lib/python3.5/site-packages/iocage/main.py", line 97, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/iocage/cli/update.py", line 68, in update_cmd
    IOCFetch(conf["cloned_release"]).fetch_update(True, uuid, tag)
  File "/usr/local/lib/python3.5/site-packages/iocage/lib/ioc_fetch.py", line 561, in fetch_update
    copy("/etc/resolv.conf", "{}/etc/resolv.conf".format(new_root))
  File "/usr/local/lib/python3.5/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root/etc/resolv.conf'
```

Similar reason seems to causing `iocage export` to fail:

```
» iocage export www
ERROR: cannot open 'zroot/iocage/jails/762a413b': dataset does not exist
usage:
        snapshot|snap [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow
```

To put it in a context - when I was playing around with iocage for the first time I created some clones unintentionally and didn't clean this up. When I tried to `zfs promote` week ago I found out that whenever I promote zfs a filesystem, another one gets dependent, keeping the same number of total clone dependencies in the filesystem - I asked about this on iocage mailling list few days ago.
Maybe some weird filesystem dependencies is the root cause. I decided to stay with the old iocage for now, however cloning entire production ZFS filesystem to my lab machine in order to work this out without time pressure. Let me know if I can help you somehow by doing some exercises.

**Comment by lukaszczerpak** [comment] 2017-02-19 09:13
After tracking down I noticed that mountpoint is still using shortened ID instead of full one and thus probably the commands break:

```
NAME                                                                        USED  AVAIL  REFER  MOUNTPOINT
zroot/iocage2/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6            3.06G  1.54T   100K  /iocage/jails/762a413b
zroot/iocage2/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root       3.06G  1.54T  2.88G  /iocage/jails/762a413b/root
```

**Comment by skarekrow** [comment] 2017-02-19 17:50
Damn! Thought this one was nailed. Yes that's exactly why the commands break, they expect the path to equal the UUID. So this is all stemming from your error above, does jail `762` have a jailed zfs dataset? That is the culprit here, and I handle the default `/data` one. But I haven't put any additional logic into handling user created ones.

**Comment by lukaszczerpak** [comment] 2017-02-19 18:15
Not sure if I got the question regarding "jailed zfs dataset". It's pretty standard jail in terms of iocage, however a bit more complicated at zfs filesystem level due to dependency on origin (I cannot get rid of by the way...). 

```
» zfs list | grep 762
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6            3.06G  1.55T   100K  /iocage/jails/762a413b
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root       3.06G  1.55T  2.88G  /iocage/jails/762a413b/root
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root/data   112K  1.55T    96K  none
```

**Comment by skarekrow** [comment] 2017-02-19 18:17
Interesting, yes you have a jailed dataset at `/root/data`. Which *should* have been migrated. You won't be able to get rid of origin, otherwise it would be a thickjail :D

So the only difference with this jail and the ones you showed me before are that it's a clone? So it is a standard clone jail with `hack88` enabled correct?

**Comment by lukaszczerpak** [comment] 2017-02-19 18:20
```
» iocage get hack88 762a413b-d4f2-11e5-b13a-003048f8f8e6
1
```

and

```
» zfs get origin | grep jails | grep 762
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6                                            origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6@a07a28ae-d4f1-11e5-b13a-003048f8f8e6       origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6@762a413b-d4f2-11e5-b13a-003048f8f8e6       origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root                                       origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root@a07a28ae-d4f1-11e5-b13a-003048f8f8e6  origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root@762a413b-d4f2-11e5-b13a-003048f8f8e6  origin    -                                                                                                  -
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root/data                                  origin    -                                                                                                  -
zroot/iocage/jails/7fde4ec2-d4f2-11e5-b13a-003048f8f8e6                                            origin    zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6@762a413b-d4f2-11e5-b13a-003048f8f8e6       -
zroot/iocage/jails/7fde4ec2-d4f2-11e5-b13a-003048f8f8e6/root                                       origin    zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root@762a413b-d4f2-11e5-b13a-003048f8f8e6  -
zroot/iocage/jails/a07a28ae-d4f1-11e5-b13a-003048f8f8e6                                            origin    zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6@a07a28ae-d4f1-11e5-b13a-003048f8f8e6       -
zroot/iocage/jails/a07a28ae-d4f1-11e5-b13a-003048f8f8e6/root                                       origin    zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6/root@a07a28ae-d4f1-11e5-b13a-003048f8f8e6  -
```

**Comment by lukaszczerpak** [comment] 2017-02-19 18:23
I think I got into the trap with zfs and I have a gut feeling that it may contribute to the issue. Trying to convert all clone jails to full ones. Once I get it done I will try to migrate to the new iocage.

Also I got some problems with the old iocage and `iocage update` - after creating `iocage-....` snapshot nothing happens, but not sure if it's related or not. Just a side comment.

**Comment by skarekrow** [comment] 2017-02-19 19:04
Interesting, I wouldn't be able to hazard a guess right now on the old behavior, as that was always a bit finicky. I don't think the origins would matter, as it's just renaming the dataset, but not destroying it. But that's certainly something I haven't tested, so if promoting a jail to become the parent causes all these issues, I'll look into mitigating that in the conversion routine as well.

Thanks for all the testing, I look forward to hear what your results are before I move forward.

**Comment by lukaszczerpak** [comment] 2017-02-19 19:19
Thanks. This may take a while. I found that `zfs promote` only flips parent-child relation and all my attempts to ditch origin failed. I tried `zfs send -R ... | zfs recv -d ...` as well.

**Comment by skarekrow** [comment] 2017-02-19 19:21
Perhaps it's best to send one dataset at a time and not recursively, as that would likely retain this relationship.

So snap and send `/iocage/jails/UUID` and then snap and send `/iocage/jails/UUID/root` under that. Then painfully rinse and repeat!

**Comment by lukaszczerpak** [comment] 2017-02-19 19:26
That's a good idea. Let me try this! Thanks!

**Comment by lukaszczerpak** [comment] 2017-02-19 20:45
Ok, there is a partial success - at least with getting rid of origins. I followed your advice (thanks!) and exported every single fs to a separate file. After that I removed all jails and imported all the filesystems back into `zroot/iocage/jails`.

Here is a script I used to get this done (not ideal, but does what I needed):

```
# shutdown jails
iocage rcshutdown

# take snapshot
zfs snapshot -r zroot/iocage/jails@cleanup

# "export" jails, each dataset individually
for fs in $(iocage list | tail -n +2 | awk '{print $2}') ; do
  zfs send -p zroot/iocage/jails/${fs}@cleanup | gzip -c > ${fs}
  zfs send -p zroot/iocage/jails/${fs}/root@cleanup | gzip -c > ${fs}-root
  zfs send -p zroot/iocage/jails/${fs}/root/data@cleanup | gzip -c > ${fs}-root-data
done

# remove all jails
for fs in $(iocage list | tail -n +2 | awk '{print $2}') ; do
  zfs destroy -R zroot/iocage/jails/${fs}
done

# "import" jails from the files
for fs in $(ls -1 | egrep -v "(root|data)") ; do
  zcat ${fs} | zfs recv zroot/iocage/jails/${fs}
  zcat ${fs}-root | zfs recv zroot/iocage/jails/${fs}/root
  zcat ${fs}-root-data | zfs recv zroot/iocage/jails/${fs}/root/data
done

# some cleanup work may be necessary to remove `@cleanup` snapshot for instance
# ...
```

IMHO next step should be to update mountpoints to full UUID and install the new iocage (0.9.6) to check if everything works fine. If you have any suggestions let me know.

**Comment by skarekrow** [comment] 2017-02-19 20:46
You shouldn't have to adjust mount points if you still want them to be short as my migration *should* do that. But yes it looks like you're close!

**Comment by lukaszczerpak** [comment] 2017-02-19 20:51
Let me take a backup of current entire `zroot/iocage` filesystem so I can try multiple approaches.

**Comment by skarekrow** [comment] 2017-02-19 20:56
\m/ thanks for all the testing :)

**Comment by lukaszczerpak** [comment] 2017-02-19 21:33
Indeed no need to adjust mount points! All worked like a charm. Thank you very much for all the help and great software!!!

```
frodong# iocage list
hack88 is no longer supported.
zroot/iocage/jails/762a413b-d4f2-11e5-b13a-003048f8f8e6 is being converted to zroot/iocage/jails/762a413b permanently.
hack88 is no longer supported.
zroot/iocage/jails/7b43467a-d4f2-11e5-b13a-003048f8f8e6 is being converted to zroot/iocage/jails/7b43467a permanently.
hack88 is no longer supported.
zroot/iocage/jails/7fde4ec2-d4f2-11e5-b13a-003048f8f8e6 is being converted to zroot/iocage/jails/7fde4ec2 permanently.
+-----+----------+-------+-----------+--------------+-----------------+
| JID |   UUID   | STATE |    TAG    |   RELEASE    |       IP4       |
+=====+==========+=======+===========+==============+=================+
| -   | a07a28ae | down  | tag1      | 10.3-RELEASE | a.b.c.d |
+-----+----------+-------+-----------+--------------+-----------------+
| -   | 7b43467a | down  | tag2      | 10.3-RELEASE | a.b.c.d |
+-----+----------+-------+-----------+--------------+-----------------+
| -   | 34f25ce3 | down  | tag3      | 10.3-RELEASE | a.b.c.d |
+-----+----------+-------+-----------+--------------+-----------------+
| -   | 7fde4ec2 | down  | tag4      | 10.3-RELEASE | a.b.c.d |
+-----+----------+-------+-----------+--------------+-----------------+
| -   | 762a413b | down  | tag5      | 10.3-RELEASE | a.b.c.d |
+-----+----------+-------+-----------+--------------+-----------------+
```

**Comment by skarekrow** [comment] 2017-02-19 21:35
Woot! I think I will leave this open to remind myself to check for clones like that. It's a nasty error you had to deal with. 

Thanks again!

**Comment by skarekrow** [comment] 2017-02-25 09:31
Hmm, I created 3 clonejails with iocage_legacy, promoted one of them and then tried the migration. It all worked as expected :/

Will try with a few more fun promotions to properly jostle things, perhaps you have a better idea of precisely what you did that landed you in this situation :D

Otherwise I may come back and close this if I can't reproduce it.

**Comment by skarekrow** [comment] 2017-02-25 09:35
Yeah, even promoting in a fun order to get the RELEASE dataset completely out of the picture, I couldn't replicate this. It all migrates just fine.

```
zroot/iocage/jails/7006266a-fb3d-11e6-9efb-2bd85b82286d@7006266a-fb3d-11e6-9efb-2bd85b82286d         64K      -    96K  -
zroot/iocage/jails/7006266a-fb3d-11e6-9efb-2bd85b82286d/root@7006266a-fb3d-11e6-9efb-2bd85b82286d   104K      -   930M  -
zroot/iocage/jails/740f9b3a-fb3d-11e6-9efb-2bd85b82286d@71d910c4-fb3d-11e6-9efb-2bd85b82286d           0      -    96K  -
zroot/iocage/jails/740f9b3a-fb3d-11e6-9efb-2bd85b82286d@740f9b3a-fb3d-11e6-9efb-2bd85b82286d           0      -    96K  -
zroot/iocage/jails/740f9b3a-fb3d-11e6-9efb-2bd85b82286d/root@71d910c4-fb3d-11e6-9efb-2bd85b82286d      0      -   930M  -
zroot/iocage/jails/740f9b3a-fb3d-11e6-9efb-2bd85b82286d/root@740f9b3a-fb3d-11e6-9efb-2bd85b82286d      0      -   930M  -
```

Perhaps this is a red herring and there was some other problem that got solved in the meantime?

Anyhow, this is here for archival purposes in case anyone has this issue down the road.

Thanks!

**Closed as completed by skarekrow** 2017-02-25 09:35 UTC
Labels: bug

**Comment by lukaszczerpak** [comment] 2017-02-25 13:00
Since that time it never occurred again, and I was playing around with migrations a lot during testing other features... I have no idea why this had happened and fully agree on to close this issue. Thanks for double checking!
