### ISSUE TITLE
iocage activate KeyError: 

### ISSUE THREAD

**Issue by kitten77** [iocage/iocage#104] opened 2017-04-12 07:15 UTC
root@gaia:~ # iocage --version
Version 0.9.7 2017/03/08

root@gaia:~ # iocage activate gaia
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/iocage/main.py", line 90, in main
    cli(obj=MODULES)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/activate.py", line 23, in activate_cmd
    ds.properties[prop].value = "yes"
  File "libzfs.pyx", line 1969, in libzfs.ZFSPropertyDict.__getitem__ (libzfs.c:44587)
KeyError: 'org.freebsd.ioc:active'

root@gaia:~ # uname -a
FreeBSD gaia.g.l9 11.0-RELEASE-p8 FreeBSD 11.0-RELEASE-p8 #0: Wed Feb 22 06:12:04 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

something you have seen before? 

root@gaia:~ # iocage list
Setting up zpool [gaia] for iocage usage
If you wish to change please use "iocage activate"
Creating gaia/iocage
Creating gaia/iocage/download
Creating gaia/iocage/images
Creating gaia/iocage/jails
Creating gaia/iocage/log
Creating gaia/iocage/releases
Creating gaia/iocage/templates
+-----+------+-------+-----+---------+-----+
| JID | UUID | STATE | TAG | RELEASE | IP4 |
+=====+======+=======+=====+=========+=====+
+-----+------+-------+-----+---------+-----+

seems like if you run iocage activate as the first command it fails.

**Comment by skarekrow** [comment] 2017-04-12 07:17
This is a duplicate of #102

**Closed as completed** 2017-04-12 07:17 UTC
Labels: duplicate
