### ISSUE TITLE
iocage fetch exception

### ISSUE THREAD

**Issue by reelsense** [iocage/iocage#376] opened 2017-10-05 07:35 UTC
Make sure to follow and check these boxes before submitting an issue! Thank you.

- [x] Supply `iocage --version` **`0.9.9.1 08/01/2017`**
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [x] Checked that the problem has not already been fixed on `master` if using
 a stable release.

```
user@virtualbox:~ % doas iocage fetch
Password:
Setting up zpool [iocage] for iocage usage
 If you wish to change please use "iocage activate"

Creating iocage/iocage
Creating iocage/iocage/download
Creating iocage/iocage/images
Creating iocage/iocage/jails
Creating iocage/iocage/log
Creating iocage/iocage/releases
Creating iocage/iocage/templates
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 474, in fetch_ftp_release
    self.fetch_download(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 701, in fetch_download
    unit_scale="mega")
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 867, in __init__
    self.postfix, unit_divisor))
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 339, in format_meter
    frac = n / total
TypeError: unsupported operand type(s) for /: 'str' and 'str'
```

I thought, _"maybe it's an issue with_ `doas`_"_.

```
user@virtualbox:~ % su
Password:
root@virtualbox:/home/user # iocage fetch
[0] 9.3-RELEASE (EOL)
[1] 10.1-RELEASE (EOL)
[2] 10.2-RELEASE (EOL)
[3] 10.3-RELEASE
[4] 10.4-RELEASE
[5] 11.0-RELEASE
[6] 11.1-RELEASE

Type the number of the desired RELEASE
Press [Enter] to fetch the default selection: (11.1-RELEASE)
Type EXIT to quit: 
Fetching: 11.1-RELEASE

Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 95, in cli
    ioc.IOCage().fetch(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 754, in fetch
    ioc_fetch.IOCFetch(release, **kwargs).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 264, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 475, in fetch_ftp_release
    missing = self.__fetch_check__(ftp_list, ftp=True)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 566, in __fetch_check__
    if hashes[f] != sha256.hexdigest():
KeyError: 'base.txz'
root@virtualbox:/home/user # exit
```

`iocage_legacy` just seems to work. Every time I've touch the current versions of `iocage` it seems temperamental.

Here is my entire scripted install history.

`echo $0 ; chsh -s /bin/csh ; csh ; echo $0`

```
su root -c "pkg update ; pkg audit -F ; pkg update ; pkg upgrade ; freebsd-version ; freebsd-update fetch ; freebsd-update install ; freebsd-version ;  pkg install doas signify nano vim-lite screen tmux py36-iocage py27-speedtest-cli mtr-nox11 nmap ca_root_nss pv py27-fail2ban ; echo "#Permit wheel group temporary doas and ask for password every time" > /usr/local/etc/doas.conf ; echo "permit setenv { PKG_PATH ENV PS1 SSH_AUTH_SOCK } :wheel" >> /usr/local/etc/doas.conf ; echo "zfs_enable="YES"" >> /etc/rc.conf ; echo "iocage_enable="YES"" >> /etc/rc.conf ; service zfs start ; sysctl kern.disks"
```

`doas zpool create iocage mirror xbd1 xbd2 ; zpool status`

`mount -t fdescfs fdesc /dev/fd`

`doas iocage fetch`

**Comment by skarekrow** [comment] 2017-10-05 10:38
Yes betas are tempermental, things happen, dragons be hidden, etc ;)

Dupe of https://github.com/iocage/iocage/issues/302

**Closed as completed by skarekrow** 2017-10-05 10:38 UTC
Labels: duplicate
