### ISSUE TITLE
jail_zfs_dataset set jailed=off when stopping jail?

### ISSUE THREAD

**Issue by rpepr** [iocage/iocage#152] opened 2015-07-27 14:24 UTC
I noticed that when I use jail_zfs_dataset=tank/mydata that iocage sets jailed=on for tank/mydata when the jail is first started. Stopping the jail does not set jailed=off on tank/mydata though. This was confusing to me at first since stopping the jail did not return control of the jail to the parent system.

Having iocage revert the dataset to jailed=off when stopping the containing jail should be a minor change, and not critical, but could improve usability. If I'm missing an important reason for the current behavior then please disregard this.

Thanks

RP

**Comment by pannon** [comment] 2015-07-27 19:47
We don't turn off `jailed` after stopping the jail by design. Mostly because of mount points you might have configured inside the jail itself. These could potentially cause confusion especially is you have a lot of jails with jailed datasets.

**Comment by skarekrow** [comment] 2015-07-30 21:53
Closing this, feel free to reopen.

**Closed by skarekrow** 2015-07-30 21:53 UTC
Labels: question
