### ISSUE TITLE
error message is not friendly when fetch from ftp blocked by firewall

### ISSUE THREAD

**Issue by amutu** [iocage/iocage#289] opened 2017-07-17 11:02 UTC
My host has pf rules that block output connections，iocage fetch will report python stack instead of meaningfull message. Temp remove the pf rule make iocage fetch happy.

iocage --version
Version	0.9.8.1 05/23/2017

iocage fetch
Creating zroot/iocage
Creating zroot/iocage/download
Creating zroot/iocage/images
Creating zroot/iocage/jails
Creating zroot/iocage/log
Creating zroot/iocage/releases
Creating zroot/iocage/templates
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 230, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 383, in fetch_ftp_release
    ftp_list = ftp.nlst()
  File "/usr/local/lib/python3.6/ftplib.py", line 557, in nlst
    self.retrlines(cmd, files.append)
  File "/usr/local/lib/python3.6/ftplib.py", line 466, in retrlines
    with self.transfercmd(cmd) as conn, \
  File "/usr/local/lib/python3.6/ftplib.py", line 397, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.6/ftplib.py", line 359, in ntransfercmd
    source_address=self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
PermissionError: [Errno 1] Operation not permitted
root@fbhk2:/usr/ports/sysutils/py3-iocage # iocage fetch
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/fetch.py", line 135, in cli
    eol=eol, files=files).fetch_release()
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 230, in fetch_release
    self.fetch_ftp_release(eol, _list=_list)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_fetch.py", line 383, in fetch_ftp_release
    ftp_list = ftp.nlst()
  File "/usr/local/lib/python3.6/ftplib.py", line 557, in nlst
    self.retrlines(cmd, files.append)
  File "/usr/local/lib/python3.6/ftplib.py", line 466, in retrlines
    with self.transfercmd(cmd) as conn, \
  File "/usr/local/lib/python3.6/ftplib.py", line 397, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.6/ftplib.py", line 359, in ntransfercmd
    source_address=self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
PermissionError: [Errno 1] Operation not permitted

**Comment by skarekrow** [comment] 2017-07-17 22:42
Basically a dupe of #165

**Closed as completed by skarekrow** 2017-07-17 22:42 UTC
Labels: duplicate
