### ISSUE TITLE
VNET stopped working on FreeNAS 11.0-Stable U4

### ISSUE THREAD

**Issue by StarkJohan** [iocage/iocage#385] opened 2017-10-08 18:09 UTC
Version	0.9.8.1 05/23/2017

I had VNET for a jail working for a while (FreeNAS 11.0-Stable U2). Upgraded to FreeNAS 11.0-Stable U4) and networking for the jail stopped working. Can't access default router or resolve names anymore. Tried booting back to U2 but issue remains.

Netstat output and all settings for the jail. Can't seem to figure out what might hav e changed.

Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            10.10.40.1         UGS       vnet0
10.10.40.0/24      link#2             U         vnet0
10.10.40.40        link#2             UHS         lo0
127.0.0.1          link#1             UH          lo0

Internet6:
Destination                       Gateway                       Flags     Netif Expire
::/96                             ::1                           UGRS        lo0
::1                               link#1                        UH          lo0
::ffff:0.0.0.0/96                 ::1                           UGRS        lo0
fe80::/10                         ::1                           UGRS        lo0
fe80::%lo0/64                     link#1                        U           lo0
fe80::1%lo0                       link#1                        UHS         lo0
ff02::/16                         ::1                           UGRS        lo0

CONFIG_VERSION:6
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:0
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
available:readonly
basejail:no
boot:off
bpf:off
children_max:0
cloned_release:11.0-RELEASE
comment:none
compression:lz4
compressratio:readonly
coredumpsize:off
count:1
cpuset:off
cputime:off
datasize:off
dedup:off
defaultrouter:10.10.40.1
defaultrouter6:none
devfs_ruleset:4
dhcp:off
enforce_statfs:2
exec_clean:1
exec_fib:0
exec_jail_user:root
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_system_jail_user:0
exec_system_user:root
exec_timeout:60
host_domainname:none
host_hostname:439669ba-9f7f-4226-bc16-c558bdbdb408
host_hostuuid:439669ba-9f7f-4226-bc16-c558bdbdb408
host_time:yes
hostid:00000000-0000-0000-0000-0cc47a342484
interfaces:vnet0:bridge0
ip4:new
ip4_addr:vnet0|10.10.40.40/24
ip4_saddrsel:1
ip6:new
ip6_addr:none
ip6_saddrsel:1
jail_zfs:off
jail_zfs_dataset:iocage/jails/439669ba-9f7f-4226-bc16-c558bdbdb408/data
jail_zfs_mountpoint:none
last_started:2017-10-08 17:56:09
login_flags:-f root
mac_prefix:02ff60
maxproc:off
memorylocked:off
memoryuse:off
mount_devfs:1
mount_fdescfs:1
mount_linprocfs:0
mount_procfs:0
mountpoint:readonly
msgqqueued:off
msgqsize:off
nmsgq:off
notes:none
nsemop:off
nshm:off
nthr:off
openfiles:off
origin:readonly
owner:root
pcpu:off
priority:99
pseudoterminals:off
quota:none
release:11.0-RELEASE-p10
reservation:none
resolver:nameserver 10.10.40.1
rlimits:off
securelevel:2
shmsize:off
stacksize:off
stop_timeout:30
swapuse:off
sync_state:none
sync_target:none
sync_tgt_zpool:none
sysvmsg:new
sysvsem:new
sysvshm:new
tag:Transmission
template:no
type:jail
used:readonly
vmemoryuse:off
vnet:on
vnet0_mac:02ff60000000,02ff60000001
vnet1_mac:none
vnet2_mac:none
vnet3_mac:none
wallclock:off

**Comment by skarekrow** [comment] 2017-10-10 02:36
Well that's a very old version of iocage that's bundled in that FreeNAS version, the newer one will be soon. That being said, this is likely because a bridge device isn't being created on startup for your vnet adapter to attach to. So you can either upgrade iocage manually, or create a bridge0 on startup for the vnet interfaces to properly connect.

**Comment by StarkJohan** [comment] 2017-10-10 04:35
I figured it is an old version but I don't know how to manually update iocage on the FreeNAS host or if it is advisable. I'd have to build the sources and replace the binary I guess as the FreeNAS host port/package handling is very restricted. Is that a correct assumption? Any particular build options needed or recommended?

Do you mean that the bridge0 interface seems to be missing on startup of the host or of the jail?

ifconfig host:
```
igb0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=2400b9<RXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,VLAN_HWTSO,RXCSUM_IPV6>
ether 0c:c4:7a:34:24:84
inet 10.10.10.11 netmask 0xffffff00 broadcast 10.10.10.255 
inet 10.10.10.111 netmask 0xffffff00 broadcast 10.10.10.255 
inet 10.10.10.12 netmask 0xffffff00 broadcast 10.10.10.255 
nd6 options=9<PERFORMNUD,IFDISABLED>
media: Ethernet autoselect (1000baseT <full-duplex>)
status: active

igb1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500 options=6403bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,VLAN_HWTSO,RXCSUM_IPV6,TXCSUM_IPV6>
ether 0c:c4:7a:34:24:85
nd6 options=9<PERFORMNUD,IFDISABLED>
media: Ethernet autoselect (1000baseT <full-duplex>)
status: active

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
inet6 ::1 prefixlen 128 
inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 
inet 127.0.0.1 netmask 0xff000000 
nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
groups: lo 

vlan4: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=200001<RXCSUM,RXCSUM_IPV6>
ether 0c:c4:7a:34:24:84
nd6 options=9<PERFORMNUD,IFDISABLED>
media: Ethernet autoselect (1000baseT <full-duplex>)
status: active
vlan: 4 vlanpcp: 0 parent interface: igb0
groups: vlan 

bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
ether 02:cf:68:30:cb:00
nd6 options=9<PERFORMNUD,IFDISABLED>
groups: bridge 
id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
member: vnet0:11 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP> ifmaxaddr 0 port 7 priority 128 path cost 2000
member: epair0a flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP> ifmaxaddr 0 port 6 priority 128 path cost 2000
member: igb0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP> ifmaxaddr 0 port 1 priority 128 path cost 20000

epair0a: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=8<VLAN_MTU>
ether 02:ff:e0:00:06:0a
nd6 options=1<PERFORMNUD>
media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
status: active
groups: epair 

vnet0:11: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
description: associated with jail: 439669ba-9f7f-4226-bc16-c558bdbdb408 (Transmission)
options=8<VLAN_MTU>
ether 02:ff:60:00:00:00
nd6 options=1<PERFORMNUD>
media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
status: active
groups: epair

```
ifconfig jail:
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
inet6 ::1 prefixlen 128 
inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
inet 127.0.0.1 netmask 0xff000000 
nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
groups: lo 

vnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
options=8<VLAN_MTU>
ether 02:ff:60:00:00:01
inet 10.10.40.40 netmask 0xffffff00 broadcast 10.10.40.255 
nd6 options=1<PERFORMNUD>
media: Ethernet 10Gbase-T (10Gbase-T <full-duplex>)
status: active
groups: epair
```

**Comment by skarekrow** [comment] 2017-10-10 04:40
Yeah building it manually will be a huge PITA, it may be best to hold tight, or use your jails in a VM of a native freebsd install in the meantime (I know :(). Unfortunately at this time iocage is essentially a "tech" preview for FreeNAS until it's officially in the GUI. So weird workarounds like this are the only solution.

I don't see bridge0 in that output, but I could be missing it.

Try issuing as root `ifconfig bridge0 create addm igb0` and try starting your jails.

**Comment by StarkJohan** [comment] 2017-10-10 04:45
bridge0 is third from the bottom in the first code block (on the host), I tidied them up a bit for readability. igb0 is a member.

**Comment by skarekrow** [comment] 2017-10-10 04:48
Ah! I see that now. Ok, so just to clarify, how are you testing that you have no network access with this jail? It looks correct so far to me

**Comment by StarkJohan** [comment] 2017-10-10 04:54
I can't reach the service running on the jail from the outside (Transmission web GUI on port 9090). This has worked like a charm on U2 and it is reachable if I turn vnet=off and use ip4_addr=igb0/<ip>. I can't ping anything other than localhost/10.10.40.40 from inside the jail including the drefaultrouter=10.10.40.1 (worked fine on U2) and I can't resolve any domain names (using wget for example) from inside the jail.

**Comment by skarekrow** [comment] 2017-10-10 04:59
Well pinging won't work unless `allow_raw_sockets` is set to `1`. I'm really not sure what the issue is, as networking is easily my weakest subject. The routes all look correct, but just to troubleshoot, have you tried changing the jails IP address, defaultrouter and nameserver to be on the same subnet as the host with vnet? It may help narrow down where things are going awry. This may be a FreeNAS issue of some sort that I'm not aware of, so I'll ping @william-gr and see if he notices anything as well

**Comment by StarkJohan** [comment] 2017-10-10 06:59
```
sudo iocage set ip4_addr="vnet0|10.10.10.40/24" JAIL
sudo iocage set resolver=none JAIL
sudo iocage set defaultrouter="10.10.10.1" JAIL
```

After issuing the above commands networking is up again as expected (and ping works from within the jail). Note that 10.10.10.1 is the default router for the FreeNAS host. VNET is still ON. Hope this helps to figure out the issue.

To clarify, this also works:

```
sudo iocage set resolver="nameserver 10.10.10.1" JAIL
```

**Comment by skarekrow** [comment] 2017-10-11 06:53
Err that's totally odd. But I'll close this as cannot repro I suppose, glad everything is working!

**Closed as completed by skarekrow** 2017-10-11 06:53 UTC
Labels: can't reproduce

**Comment by StarkJohan** [comment] 2017-10-11 07:03
Well, it's not working as I need the jail to use a different default router (and thus different VLAN). I moved it to the same subnet as you suggested for troubleshooting only... That works but the issue still remains when setting it back to the alternate default router as it was before the U4 update.

Seems like the next step is building from source unless @william-gr has any other suggestions.

**Comment by johnramsden** [comment] 2017-12-27 03:31
My VNET has stopped working on FreeNAS11.1. Everything was all up and running fine yesterday, and today after reboot, creating a new jail, the network my jails used to use has stopped working. It's not working on both new jails I create and old jails. I can't figure out what the problem could be.

Here's my config:

```
CONFIG_VERSION:9
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:1
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
available:readonly
basejail:no
boot:on
bpf:no
children_max:0
cloned_release:11.1-RELEASE
comment:none
compression:lz4
compressratio:readonly
coredumpsize:off
count:1
cpuset:off
cputime:off
datasize:off
dedup:off
defaultrouter:172.20.40.1
defaultrouter6:none
depends:none
devfs_ruleset:4
dhcp:off
enforce_statfs:2
exec_clean:1
exec_fib:0
exec_jail_user:root
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_system_jail_user:0
exec_system_user:root
exec_timeout:60
host_domainname:none
host_hostname:unifi.ramsden.network
host_hostuuid:unifi
host_time:yes
hostid:5c8a3f6f-989f-11e6-8d50-0cc47a696994
interfaces:vnet1:bridge1
ip4:new
ip4_addr:vnet1|172.20.40.20/24
ip4_saddrsel:1
ip6:new
ip6_addr:none
ip6_saddrsel:1
jail_zfs:off
jail_zfs_dataset:data/unifi/data
jail_zfs_mountpoint:
last_started:2017-12-27 02:36:01
login_flags:-f root
mac_prefix:02ff60
maxproc:off
memorylocked:off
memoryuse:off
mount_devfs:1
mount_fdescfs:1
mount_linprocfs:1
mount_procfs:0
mountpoint:readonly
msgqqueued:off
msgqsize:off
nmsgq:off
notes:none
nsemop:off
nshm:off
nthr:off
openfiles:off
origin:readonly
owner:root
pcpu:off
priority:99
pseudoterminals:off
quota:none
release:11.1-RELEASE-p6
reservation:none
resolver:search ramsden.network;nameserver 172.20.40.1;nameserver 8.8.8.8
rlimits:off
securelevel:2
shmsize:off
stacksize:off
state:up
stop_timeout:30
swapuse:off
sync_state:none
sync_target:none
sync_tgt_zpool:none
sysvmsg:new
sysvsem:new
sysvshm:new
template:no
type:jail
used:readonly
vmemoryuse:off
vnet:on
vnet0_mac:02ff608700b4,02ff608700b5
vnet1_mac:02ff60680091,02ff60680092
vnet2_mac:none
vnet3_mac:none
wallclock:off
```

**Comment by johnramsden** [comment] 2017-12-27 03:33
I'm wondering if I could have a similar problem.

My VNET has stopped working on FreeNAS11.1. Everything was all up and running fine yesterday, and today after reboot, creating a new jail, the network my jails used to use has stopped working. It's not working on both new jails I create and old jails. I can't figure out what the problem could be.

Here's my config:

```
CONFIG_VERSION:9
allow_chflags:0
allow_mount:0
allow_mount_devfs:0
allow_mount_nullfs:0
allow_mount_procfs:0
allow_mount_tmpfs:0
allow_mount_zfs:0
allow_quotas:0
allow_raw_sockets:1
allow_set_hostname:1
allow_socket_af:0
allow_sysvipc:0
available:readonly
basejail:no
boot:on
bpf:no
children_max:0
cloned_release:11.1-RELEASE
comment:none
compression:lz4
compressratio:readonly
coredumpsize:off
count:1
cpuset:off
cputime:off
datasize:off
dedup:off
defaultrouter:172.20.40.1
defaultrouter6:none
depends:none
devfs_ruleset:4
dhcp:off
enforce_statfs:2
exec_clean:1
exec_fib:0
exec_jail_user:root
exec_poststart:/usr/bin/true
exec_poststop:/usr/bin/true
exec_prestart:/usr/bin/true
exec_prestop:/usr/bin/true
exec_start:/bin/sh /etc/rc
exec_stop:/bin/sh /etc/rc.shutdown
exec_system_jail_user:0
exec_system_user:root
exec_timeout:60
host_domainname:none
host_hostname:unifi.ramsden.network
host_hostuuid:unifi
host_time:yes
hostid:5c8a3f6f-989f-11e6-8d50-0cc47a696994
interfaces:vnet1:bridge1
ip4:new
ip4_addr:vnet1|172.20.40.20/24
ip4_saddrsel:1
ip6:new
ip6_addr:none
ip6_saddrsel:1
jail_zfs:off
jail_zfs_dataset:data/unifi/data
jail_zfs_mountpoint:
last_started:2017-12-27 02:36:01
login_flags:-f root
mac_prefix:02ff60
maxproc:off
memorylocked:off
memoryuse:off
mount_devfs:1
mount_fdescfs:1
mount_linprocfs:1
mount_procfs:0
mountpoint:readonly
msgqqueued:off
msgqsize:off
nmsgq:off
notes:none
nsemop:off
nshm:off
nthr:off
openfiles:off
origin:readonly
owner:root
pcpu:off
priority:99
pseudoterminals:off
quota:none
release:11.1-RELEASE-p6
reservation:none
resolver:search ramsden.network;nameserver 172.20.40.1;nameserver 8.8.8.8
rlimits:off
securelevel:2
shmsize:off
stacksize:off
state:up
stop_timeout:30
swapuse:off
sync_state:none
sync_target:none
sync_tgt_zpool:none
sysvmsg:new
sysvsem:new
sysvshm:new
template:no
type:jail
used:readonly
vmemoryuse:off
vnet:on
vnet0_mac:02ff608700b4,02ff608700b5
vnet1_mac:02ff60680091,02ff60680092
vnet2_mac:none
vnet3_mac:none
wallclock:off
```

**Comment by StarkJohan** [comment] 2017-12-27 06:41
My problem was solved after updating to 11.1.

What is your desired jail network setup? I'm yet to get "virtual" VLAN tagging to work so I've resorted to using a second NIC for my "second" VLAN and using my switch to do the VLAN sorting.

That being said, have a look at the bridge setup for your FreeNAS host. To get vnet-stuff to run using a separate "defaultrouter" I've had to setup the bridges manually to connect vnet interface to the proper NIC as it is non standard. Maybe that is a part of your problem as well? 

It doesn't work (for me at least) to disable vnet and e.g. set "ip4_addr:igb1|10.10.40.40/24" as this still directs the traffic over igb0. 

I have a bunch of jails running fine without vnet and the following bridge I have to manually setup after each reboot to get the single vnet jail to use igb1 instead of the standard igb0:
```
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
ether 02:cf:68:30:cb:00
nd6 options=9<PERFORMNUD,IFDISABLED>
groups: bridge 
id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
member: igb1 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 2 priority 128 path cost 20000
member: vnet0:38 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 5 priority 128 path cost 2000
```

Maybe this can guide you at least a little bit?

**Comment by johnramsden** [comment] 2017-12-27 06:54
I'm on freenas 11.1 as well.

I'm not using any vlan tagging on freenas. I'm doing all my VLAN tagging on switches.

Unfortunately I need some VNET functionality or I would just be using my NIC directly.

This is my exact setup:

```
iocage create --release 11.1-RELEASE --name unifi \
          allow_raw_sockets="1" \
          mount_linprocfs="1" \
          boot="on" vnet=on \
          ip4_addr="vnet1|172.20.40.20/24" \
          interfaces="vnet1:bridge1" \
          defaultrouter="172.20.40.1"
```

`bridge1` one already existed on my system, I would assume for the old style jails.

---

So in looking for the problem to post this information I noticed that when I set up the system I only had `bridge0` and `bridge1`, which were each tied to `igb0` and `igb1` respectively. Now I noticed I have `bridge2` to as well, which seems to be tied to `igb1`. So somehow after rebooting `bridge1` is no longer tied to my interface. I'm not sure what would have caused this. I'm going to try tying the nic to `bridge2` and see if that fixes the problem.

**Comment by StarkJohan** [comment] 2017-12-27 07:01
What bridges do you have except for bridge1 and what is their composition?
Try destroying all bridges, recreate the one(s) you need and rebooting your jails.

**Comment by johnramsden** [comment] 2017-12-27 07:06
I haven't created any bridges by hand actually. FreeNAS creates bridges itself and I've just been using them.

I'm sure that would work I just want to be sure it stays working once I reboot.

**Comment by johnramsden** [comment] 2017-12-27 07:10
So, as I expected I just needed to set it to the bridge that was using the interface. For some reason when I rebooted freenas decided to create `bridge2` instead of `bridge0` and `bridge1`.

**Comment by StarkJohan** [comment] 2017-12-27 08:08
Yeah, something in the bridge creation process seems to be a bit off or not as logical as I would like it to be.
