### ISSUE TITLE
iocage start/stop with vnet disrupts host netwokring

### ISSUE THREAD

**Issue by Licenser** [iocage/iocage#84] opened 2017-03-22 02:31 UTC
When starting/stopping a jail the host network is interrupted for a few seconds:

![image](https://cloud.githubusercontent.com/assets/119093/24179548/154b3842-0eb0-11e7-96df-1db356267322.png)

**Comment by skarekrow** [comment] 2017-03-22 11:16
Interesting, I don't see that behavior. What does your network setup look like? The hosts version?

I'm on `CURRENT` and the issue does not manifest.

**Comment by Licenser** [comment] 2017-03-22 11:42
Oh now I pretend I know what CURRENT is ^.^ I think I'm not I'm using the 11.0-RELEASE

```
FreeBSD fifo-bsd 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r315439: Fri Mar 17 07:52:09 CET 2017     root@fifo-bsd:/usr/obj/usr/src/sys/FIFOKERNEL  amd64
```

where the kernel is the default config plus:
```
nooptions       SCTP   # Stream Control Transmission Protocol
options         VIMAGE # VNET/Vimage support
options         RACCT  # Resource containers
options         RCTL   # same as above
```

**Comment by skarekrow** [comment] 2017-03-22 11:43
Oh `CURRENT` is the HEAD of FreeBSD Development. 

Can you paste a sanitized version of your `rc.conf` and `ifconfig` outputs too?

**Comment by Licenser** [comment] 2017-03-22 11:45
sure, sorry for being slow here ;) still new to the whole BSD thingy :D

**Comment by Licenser** [comment] 2017-03-22 11:45
```
[root@fifo-bsd ~/chunter]# ifconfig
em0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
	ether 00:25:90:a6:3b:c7
	inet 192.168.1.22 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect (1000baseT <full-duplex>)
	status: active
em1: flags=8c02<BROADCAST,OACTIVE,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
	ether 00:25:90:a6:3b:c6
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet autoselect
	status: no carrier
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
	inet 127.0.0.1 netmask 0xff000000
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo
bridge0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 02:6a:d8:fe:02:00
	nd6 options=9<PERFORMNUD,IFDISABLED>
	groups: bridge
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 32768 ifcost 0 port 0
	member: em0 flags=143<LEARNING,DISCOVER,AUTOEDGE,AUTOPTP>
	        ifmaxaddr 0 port 1 priority 128 path cost 20000
bridge1: flags=8802<BROADCAST,SIMPLEX,MULTICAST> metric 0 mtu 1500
	ether 02:6a:d8:fe:02:01
	nd6 options=9<PERFORMNUD,IFDISABLED>
	groups: bridge
	id 00:00:00:00:00:00 priority 32768 hellotime 2 fwddelay 15
	maxage 20 holdcnt 6 proto rstp maxaddr 2000 timeout 1200
	root id 00:00:00:00:00:00 priority 0 ifcost 0 port 0
```

```
[root@fifo-bsd ~/chunter]# cat /etc/rc.conf
hostname="fifo-bsd"
sshd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"


# set up two bridge interfaces for iocage
cloned_interfaces="bridge0 bridge1"

# plumb interface em0 into bridge0
ifconfig_bridge0="addm em0 up"
ifconfig_em0="up"

# Use DHCP for em0
ifconfig_em0="DHCP"
```

**Comment by skarekrow** [comment] 2017-03-22 11:47
Interesting, looks a lot like mine. I have my DHCP entry above the creation of the bridges, but you can also try setting `ifconfig_bridge0="DHCP"` instead of on `em0` and see if that resolves the behavior.

**Comment by Licenser** [comment] 2017-03-22 11:55
Well that broke my box :P I got to dig out the horrible java thingy and get back to you on this in a bit.

**Comment by Licenser** [comment] 2017-03-22 12:02
Okay my rc.conf file is hating me, it didn't brige up bridge0 or add em0 (that's probably a issue for #freebsd) but I've caught up with doing:

```
ifconfig bridge0 addm em0 up
dhcpclient bridge0
```

So after getting it all running again, with the IP on `bridge0` not `em0` the same happens.

**Comment by Licenser** [comment] 2017-03-22 12:04
Is there a reason not to try to build a `CURRENT` kernel? Might be worth checking if it's a 11 problem

**Comment by skarekrow** [comment] 2017-03-22 12:06
Ouch :/

The main argument would be stability in a production environment. I use and rely on `CURRENT` but many would slap me if I suggested someone else do that.

In FreeBSD the Kernel and World cannot be separate. So you would also need to build the userland bits with it. The [FreeBSD Handbook](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/kernelconfig.html) has an excellent chapter. You may find it a better use of your time to just install a `CURRENT` iso and try iocage from there with the same setup.

**Comment by Licenser** [comment] 2017-03-22 12:27
Oh good greif :(, I think I'll table this for the moment, I just got a single test system and am not too fond of the idea of reinstalling it or exploding it in the hope it's really 'just' a 11 issue

**Comment by skarekrow** [comment] 2017-03-22 12:29
I don't blame you, I can set up a test system, but it's low on the list of things to do right now. Perhaps somebody else will chime in who have experienced this issue or know the cause :)

**Comment by skarekrow** [comment] 2017-05-02 12:30
I can not replicate this :( This is what I [see](http://imgur.com/a/rEDcX). Going to close this unless you have a better reproduction case for me.

**Closed as completed by skarekrow** 2017-05-02 12:30 UTC
Labels: can't reproduce

**Comment by Licenser** [comment] 2017-05-02 12:32
have you tried reproducing it on 11.0-RELEASE or just CURRENT?

**Comment by skarekrow** [comment] 2017-05-02 13:10
Both. That image was 11.0-RELEASE

**Comment by Licenser** [comment] 2017-05-02 13:16
Oh I meant the host version not the image version, I don't think the image has much effect if I understand how jails work correctly.

**Comment by skarekrow** [comment] 2017-05-02 13:18
Hehe when I say image I mean the one I linked too. I tested on a CURRENT and 11.0-RELEASE host.

**Comment by Licenser** [comment] 2017-05-02 14:04
Oh buy then it's probably just a freak accident on my end :(

**Comment by skarekrow** [comment] 2017-05-02 14:06
Perhaps. If you can still recreate it and are able to recreate it on another system (a vm perhaps) then we might be overlooking something specific in your environment that does it.
