### ISSUE TITLE
rsync to jail results in kernel panic

### ISSUE THREAD

**Issue by xerovis** [iocage/iocage#309] opened 2016-01-12 23:57 UTC
We are able to replicate this without fail every time. We are running approx 50 rsync jobs pushing files to a jail and we get a kernel panic. We have not come across this issue before mostly because this is the first time we have tested this particular use case.

Host server has 96GB of RAM. Host is setup like the other 4 servers we are running with iocage, though we are not running rsync jobs to them.

We get this issue on FreeBSD 10.2-p8 RELEASE and plain old 10.2 RELEASE.

**Comment by xerovis** [comment] 2016-01-13 01:10
To add to this, we are seeing this issue on 3 servers (Hosts). The only difference between each 3 Hosts is 2 x Hosts run LSI 9211-8i cards in IT mode and the 3rd host is running a PERC6i.

**Comment by xerovis** [comment] 2016-01-13 02:05
Further to this issue: We have tested the exact same rsync job(s) directly to a host server instead of an iocage jail and we do not get any issues. To make sure we didn't get lucky we ran the same job 3 times. Maybe something in iocage is causing a kernel panic on large rsync transfers?

**Comment by skarekrow** [comment] 2016-01-13 04:33
This issue and #278 are related I believe. It seems unionfs causes a kernel panic when a lot of load is put on the system. I've been replicating this on a few different servers and have a fix that's almost ready. When that gets pushed I'll update you :)

**Comment by xerovis** [comment] 2016-01-14 00:17
Great to know you are already aware of this issue and creating a fix. Do you happen to have any idea on timeframe? I know that timeframe and software do not mix very well but this particular jail use case is pretty important to our continued use of iocage at the moment.

**Comment by skarekrow** [comment] 2016-01-14 11:49
Soon :) That's the risk associated with using the `develop` branch. Which is why it hasn't been merged as stable yet. The fixes coming in won't be migrating the basejails that you are currently using. So you will have to recreate things. You can also manually move these from the `_` folder:
```
"bin
boot
lib
libexec
rescue
sbin
usr/bin
usr/include
usr/lib
usr/libexec
usr/ports
usr/sbin
usr/share
usr/src
usr/libdata
usr/lib32
```
Into the `/root` folder of the jail as that's where the nullfs mounts will be happening. I haven't spent any time checking migrations between unionfs and the nullfs jails unfortunately. I'm only concerned with migrating the basejails created with the stable version.

**Closed** 2016-01-14 12:29 UTC
Labels: bug

**Comment by xerovis** [comment] 2016-01-14 13:05
Thanks for keeping us in the loop on this.
We don't migrate any jail data, all jails are recreated from scratch by script. We let iocage do its thing and then do things over the top of iocage.

**Comment by skarekrow** [comment] 2016-01-14 13:06
Oh that's good to hear! I was hoping that was the case. Please report back if these aren't fixed.

**Comment by xerovis** [comment] 2016-01-14 23:14
Just tested the new release and only one change to our script was required, which was very nice. Have yet to test to see if the rsync issue we were seeing no longer exists.

One thing I did notice is that /tmp permissions are not standard, which results in a number of programs failing to start.

**Comment by xerovis** [comment] 2016-01-15 00:42
We have tested the new code with the rsync jobs and the Host no longer kernel panics. Thank you for pushing through this fix!

**Comment by skarekrow** [comment] 2016-01-15 08:30
That's fantastic to hear! As for the `/tmp` permissions issue, I've heard reports but I haven't been able to reproduce on my machine.

That might be because I have to nuke things so often. Are you using RELEASEs that have been fetched with earlier `develop` commits? That might help me track this down.
