### ISSUE TITLE
iocage stop jail will remove IP from the interface and therefore will destroy CARP configuration

### ISSUE THREAD

**Issue by denigmus** [iocage/iocage#578] opened 2018-06-28 11:37 UTC
Provided:

Real public IP is already configured on em0 (via rc.conf as CARP like that: 
ifconfig_em0_alias7="inet vhid 1 pass passhere alias IP/32")

The same IP obviously assigned to the jail.

iocage start jail is not a problem

Problem:

iocage stop jail will remove this IP from interface and ruin CARP configuration. Moreover, iocage stop jail will not restore that configuration.

I couldn't find any option in config that would disallow removing IP from the interface on jail's stop.

Will you implement?
Any workaround available meanwhile?

It's just one use case, that suppose that CARP's interface is always ON independent of jail. Another use case, which I just realized is more important when CARP's interface should be restored on jail's start, **but as CARP with password from rc.conf**, not just as alias. I think there should be some config option that tells iocage to respect rc.conf and take IP configuration from there for the IP set in the jail's config. Any workaround for this too?

iocage -v
Version 1.0 ALPHA

**Comment by denigmus** [comment] 2018-06-28 11:52
Something like

Case1

```
"ip4_addr": "em0|192.1.1.1",
"ip4_addr_rcconf": "0",
"ip4_addr_keeponstop": "1",
```

Case2

```
"ip4_addr": "em0|192.1.1.1",
"ip4_addr_rcconf": "1",
"ip4_addr_keeponstop": "0",
```

**Comment by skarekrow** [comment] 2018-06-28 19:05
I personally don't use CARP, so I don't have a suggestion for this. What do you mean iocage stop jail will not restore that configuration? I think those properties since this is carp specific should probably be `carp_pass`, `carp_keeponstop` or something similar. We'd need IPv6 equivalents as well, so keeping these slightly more generic.

I likely won't be implementing this due to lack of time, but tracking it here in case somebody else wishes too (@jsegaert is a good bet so far :D)

**Comment by denigmus** [comment] 2018-06-28 20:13
I mean that it will be restored just like a normal alias, because iocage doesn't respect rc.conf, it just put an alias to interface.

It is not carp specific. CARP is just one use case. When I googled solution for this problem I've seen many other guys who just want keep IP untouched on jail's stop (keep it on interface), include for FreeNAS system. I won't claim it as bug ;), but it close to :)

It's definitely not a feature request. I strongly believe it is something that should have been there. Why iocage shut down IP? What's background for that? Does it come from assumption that IP can only be used by jail and is irrelevant without it? This assumptions is not correct then. There are few scenarios apart from carp when IP will serve other systems on the host while jail is stopped for some reasons.

Finally, even the systems's native jail -r PID will not destroy the alias. So, why iocage should do this?

**Comment by skarekrow** [comment] 2018-06-28 20:39
> I mean that it will be restored just like a normal alias, because iocage doesn't respect rc.conf, it just put an alias to interface.

iocage also doesn't respect jail.conf, that's the draw :)

> It is not carp specific. CARP is just one use case. When I googled solution for this problem I've seen many other guys who just want keep IP untouched on jail's stop (keep it on interface), include for FreeNAS system. I won't claim it as bug ;), but it close to :)

And I've had many others who wanted the opposite, this is the first somebody has directly asked me for this. So I would wager so far it has the right default, though this usecase has merit. Just not one I personally have, so no desire to spend my limited time on it :P

> Finally, even the systems's native jail -r PID will not destroy the alias. So, why iocage should do this?

It also doesn't call /etc/shutdown or do most of what iocage does. Not a valid argument ;) iocage removes the alias as we see them as jail specific. iocage sets them up, it is fit it destroys them.  To manage the whole lifecycle and not leave a mess when we're done is the goal.

**Comment by denigmus** [comment] 2018-06-29 09:46
>And I've had many others who wanted the opposite, 

So, there was a time when you trusted that not deleting IP is the correct behavior? :)
Where to take this part source code? I'm zero in python, though...

>It also doesn't ..

That's true. But why not put on config any new feature that is implemented on the top of the default system's behavior? It's a good tone. ;)

**Comment by pos42** [comment] 2018-12-30 22:59
@denigmus 
I agree with 

> That's true. But why not put on config any new feature that is implemented on the top of the default system's behavior? It's a good tone. ;)

This seems to be a duplicate of what I logged at https://github.com/iocage/iocage/issues/758

**Comment by skarekrow** [comment] 2019-01-29 19:17
@denigmus Let me know with 1.1, we switched networking to use jail(8) instead and this *should* solve your issue here

**Comment by denigmus** [comment] 2019-01-30 09:32
@skarekrow I patched in my own way, but will test in the future when configuring a new server

**Comment by skarekrow** [comment] 2019-01-30 18:12
@denigmus :+1: I'll close this in the meantime then

**Closed as completed by skarekrow** 2019-01-30 18:12 UTC
Labels: enhancement

**Comment by jSML4ThWwBID69YC** [comment] 2022-06-14 20:41
This is still an issue on FreeBSD 13.1 with Iocage 1.2_10. 

Iocage shuts down the IP when the jail stops destroying the carp configuration. Is there a way to have a jail shutdown, but leave the interface alone?
