### ISSUE TITLE
Can't modify template after creation

### ISSUE THREAD

**Issue by tehfink** [iocage/iocage#452] opened 2017-12-20 23:26 UTC
Is conversion to a template now a one-way street?

```
# iocage --version
Version 0.9.9.2 09/30/2017
# iocage create --name template-02 --pkglist=/iocage/pkgs.json -r 11.1-RELEASE boot=off allow_sysvipc=1 allow_raw_sockets=1 host_hostname=template-02 template=yes ip4_addr="lo1|172.16.10.1/28"
template-02 successfully created!
Testing SRV response to FreeBSD
Testing DNSSEC response to FreeBSD

Installing pkg... 
Installing supplied packages:
  - nano... 
  - screen... 
Message from screen-4.6.1_2:
…snipped
===========================================================================
# iocage update template-02
Please convert back to a jail before trying to update template-02
# iocage set template=no template-02
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 45, in cli
    plugin)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1359, in set
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 599, in json_set_value
    self.zfs.get_dataset(new_location).rename(old_location)
  File "libzfs.pyx", line 2106, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy
# iocage update template-02
Please convert back to a jail before trying to update template-02
# iocage stop template-02
template-02 is not running!
# iocage list -t
+-----+-------------+-------+--------------+-------------+
| JID |    NAME     | STATE |   RELEASE    |     IP4     |
+=====+=============+=======+==============+=============+
| -   | template-02 | down  | 11.1-RELEASE | 172.16.10.1 |
+-----+-------------+-------+--------------+-------------+
```

**Comment by skarekrow** [comment] 2017-12-21 03:08
Nope, looks like the jail dataset was still busy. This should have been improved in the code on GitHub, where you perhaps in the jail directory when issuing this command?

**Comment by tehfink** [comment] 2017-12-21 18:18
> where you perhaps in the jail directory when issuing this command?

Not that I was aware of. However, after a reboot, it seems to work. Thanks! Sorry for the noise.

**Comment by tehfink** [comment] 2017-12-21 18:47
Well, unfortunately I spoke too soon. I haven't created any child jails from the template, but:
```
# iocage stop template-02
* Stopping template-02
  + Running prestop OK
  + Stopping services OK
  + Removing jail process OK
  + Running poststop OK
# iocage set template=yes template-02
A template by that name already exists!
root@dyscr:~ # iocage list -t
+-----+-------------+-------+--------------+-------------+
| JID |    NAME     | STATE |   RELEASE    |     IP4     |
+=====+=============+=======+==============+=============+
+-----+-------------+-------+--------------+-------------+
```

**Comment by skarekrow** [comment] 2017-12-22 02:39
I've seen this, and I wasn't able to figure out how to reproduce it reliably. It seemed the jail was "busy" but I couldn't find anything using it. It went away after I started and stopped the jail, does yours as well?

**Comment by kitten77** [comment] 2017-12-22 09:09
Could it be a zombie process? Have seen that a couple of times, processes
that are in a state sleep do not disturb.
Had one jail i never could kill off at all because of a zombie, it was so
bad I had to reboot the server.
Took me awhile to find the process and nothing I did could kill it?

22. des. 2017 3:39 a.m. skrev "Brandon Schneider" <notifications@github.com

**Comment by francisco1844** [comment] 2018-01-17 04:09
Is there any additional info that one can provide to help troubleshoot?
Don't see a debug mode for iocage.

**Comment by imp1sh** [comment] 2018-08-01 10:07
Sometimes I cannot "set template=no" on a template.
I cannot reproduce when this happens but it does happen. The only way around it is for me to reboot the whole machine *bump*
FreeBSD 11.2
iocage Version	0.9.10 2017/12/22
This is the error:
```
root@jailhost001:~/hostcage # iocage list -t
+-----+------------------------+-------+--------------+-------------+
| JID |          NAME          | STATE |   RELEASE    |     IP4     |
+=====+========================+=======+==============+=============+
| -   | jailtemplate           | down  | 11.2-RELEASE | 10.10.133.5 |
+-----+------------------------+-------+--------------+-------------+
| -   | jailtemplatemariadb102 | down  | 11.2-RELEASE | 10.10.133.7 |
+-----+------------------------+-------+--------------+-------------+
| -   | jailtemplatephp72      | down  | 11.2-RELEASE | 10.10.133.6 |
+-----+------------------------+-------+--------------+-------------+
| -   | jailtemplatephpmyadmin | down  | 11.2-RELEASE | 10.10.133.8 |
+-----+------------------------+-------+--------------+-------------+
root@jailhost001:~/hostcage # iocage set template=no jailtemplatephp72
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 60, in cli
    exit_on_error=True, jail=jail, skip_jails=True).set(prop, plugin)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1418, in set
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 702, in json_set_value
    self.zfs.get_dataset(new_location).rename(old_location)
  File "libzfs.pyx", line 2134, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy
```

**Comment by imp1sh** [comment] 2018-08-01 21:54
I also have this under FreeNAS 11.1-U5 with iocage Version 1.0 Alpha.
I strongly assume that it's processes from within the jails that survive the jail shutdown. I dunno how this can happen. Does iocage not send kill -9 to the process if it does not halt on kill -15?
I found at least one process that I then killed of course but who wants to run through all processes on a system all the time?

On this very host I have three jails running each of them is made from a template. Even when I shut down every jail, the error still occurs.

```
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage/cli/set.py", line 60, in cli
    exit_on_error=True, jail=jail, skip_jails=True).set(prop, plugin)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/iocage.py", line 1425, in set
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage/lib/ioc_json.py", line 715, in json_set_value
    self.zfs.get_dataset(new_location).rename(old_location)
  File "libzfs.pyx", line 2164, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy

```

**Comment by gronke** [comment] 2018-08-01 22:07
libiocage had similar issues. The resolution was to unmount the ZFS Dataset before renaming it.

**Comment by skarekrow** [comment] 2018-08-02 07:03
Closed by @jsegaert and #590

**Comment by imp1sh** [comment] 2018-08-02 09:47
Can you please explain what this means skarekrow.
So we need to wait for a new version of iocage that fixes this? If so, which version?
What method  can I use to work around that problem?
I tried some `zfs unmount -f` to the zfs dataset corresponding to my jail, but that won't work at all.

**Comment by jsegaert** [comment] 2018-08-03 00:41
That's a great question actually.  

@skarekrow : Now that the FreeNAS project is using their own fork of iocage, how is it decided what commits are added to their upstream fork?  Looks like the only changes that made it to FreeNAS-BETA2 was the stuff that was committed by the iXsystems-folks.

Is there a process (or schedule) to keep these 2 forks from diverging too much and automatically add relevant commits from non-iX contributors?  Or is the direction rather that "if there's no issue logged in [redmine](https://redmine.ixsystems.com/issues/new), it won't be added to the FreeNAS fork"?

Sorry to hijack this thread, but [https://github.com/freenas/iocage](https://github.com/freenas/iocage) doesn't have their issues section active.

**Comment by skarekrow** [comment] 2018-08-03 01:09
@imp1sh Make sure the jail isn't running (`jls` command on your host) and forcefully unmount the dataset as you have been, it may require a host reboot in some rare circumstances.

@jsegaert Currently the process is like this:
- Redmine issues from FreeNAS users happen
- We need to have those fixes in and ready for our release
- We need to branch releases from iocage (up to us to maintain, makes no sense for community to do so)
- Those branches need to be tested, and iocage/iocage master is too fluid

So the process if you want certain commits you feel strongly about in FreeNAS is to create a Redmine ticket and a corresponding pr cherry picking it from iocage/iocage's master branch. Otherwise the plan is to sync iocage's tree during the next release cycle, and start all over with the process above.

The hope is better testing coverage for both freenas and iocage.

**Comment by jsegaert** [comment] 2018-08-03 01:59
Thank you; I'll log some Redmine tickets. 

More testing is better indeed  :-)

**Comment by tehfink** [comment] 2019-02-16 18:29
@skarekrow Still receiving this error:
```
# iocage list -t
+-----+------+-------+--------------+-------------+
| JID | NAME | STATE |   RELEASE    |     IP4     |
+=====+======+=======+==============+=============+
| -   | 11.2 | down  | 11.2-RELEASE | 172.16.10.1 |
+-----+------+-------+--------------+-------------+
# iocage update 11.2
Please convert back to a jail before trying to update 11.2
# iocage set template=no 11.2
Traceback (most recent call last):
  File "/usr/local/bin/iocage", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/iocage_cli/set.py", line 59, in cli
    jail=jail, skip_jails=True).set(prop, plugin)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/iocage.py", line 1578, in set
    iocjson.json_set_value(prop)
  File "/usr/local/lib/python3.6/site-packages/iocage_lib/ioc_json.py", line 1667, in json_set_value
    old_location, False, True)
  File "libzfs.pyx", line 2309, in libzfs.ZFSObject.rename
libzfs.ZFSException: Device busy
# iocage -v
Version 1.1 RELEASE 2019/01
# python3.6 -V
Python 3.6.8
# uname -a
FreeBSD example.com 11.2-RELEASE-p9 FreeBSD 11.2-RELEASE-p9 #0: Tue Feb  5 15:30:36 UTC 2019     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
# zpool list zjail
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP  HEALTH  ALTROOT
zjail  46.5G  2.36G  44.1G        -         -     9%     5%  1.00x  ONLINE  -
# zpool status zjail
  pool: zjail
 state: ONLINE
  scan: none requested
config:

        NAME        STATE     READ WRITE CKSUM
        zjail       ONLINE       0     0     0
          vtbd1     ONLINE       0     0     0

errors: No known data errors
```

**Comment by sonicaj** [comment] 2019-06-25 01:21
@tehfink i am unable to recreate this issue on latest master. Can you please confirm if this still exists ?
```
root@freenas[~]# iocage create -r 11.2-RELEASE -n jail nat=1
jail successfully created!
root@freenas[~]# iocage set template=1 jail
jail converted to a template.
root@freenas[~]# iocage update jail
Please convert back to a jail before trying to update jail
root@freenas[~]# iocage set template=0 jail
jail converted to a jail.
root@freenas[~]#
```

**Closed as completed** 2024-04-04 18:39 UTC
Labels: investigating
