### ISSUE TITLE
"iocage upgrade" after "iocage create" infinite loops

### ISSUE THREAD

**Issue by asomers** [iocage/iocage#434] opened 2017-12-03 14:37 UTC
- [x] Supply `iocage --version`
- [x] Supply the commands used, along with any steps to recreate it.
- [x] Provide the output from the command you issued.
- [x] Supply what you expected the result or output to be
- [ ] Checked that the problem has not already been fixed on `master` if using
 a stable release.

I tried creating an 11.0 jail and then upgrading it to 11.1 before doing anything else.  The upgrade proceeded normally for awhile, but then got stuck in an infinite loop.  The behavior reproduced on 2 out of 2 attempts.

```
> iocage --version
Version 0.9.9.2 09/30/2017
> sudo iocage create -r 11.0-RELEASE -u upgrade_test
upgrade_test successfully created!
> sudo iocage upgrade -r 11.1-RELEASE upgrade_test
...
src component not installed, skipped^M
No updates are available to install.^M
Run '/tmp/tmpfvftqctl fetch' first.^M
src component not installed, skipped^M
No updates are available to install.^M
Run '/tmp/tmpfvftqctl fetch' first.
...
```

**Comment by skarekrow** [comment] 2017-12-05 20:41
Duplicate of https://github.com/iocage/iocage/issues/397

**Closed as completed by skarekrow** 2017-12-05 20:41 UTC
Labels: duplicate
