### ISSUE TITLE
Update of jail after release upgrade fails

### ISSUE THREAD

**Issue by kdbruin** [iocage/iocage#332] opened 2017-08-11 11:29 UTC
iocage version: 0.9.9.1 08/01/2017

Last week I've upgraded my host system and jails from 11.0-RELEASE to 11.1-RELEASE and yesterday I wanted to install the latest updates for 11.1 using the following command:

    iocage update git

I get the following error:

    * Updating git to the latest patch level... 
    src component not installed, skipped
    Looking up updates.home.lan mirrors... none found.
    Fetching metadata signature for 11.0-RELEASE from updates.home.lan... failed. 
    No mirrors remaining, giving up.
    Error occured, 11.0-RELEASE was not updated to the latest patch level.

How can I update my jail to the latest patch level?

**Comment by johnramsden** [comment] 2017-08-12 06:54
Maybe this is the same as [this issue](https://github.com/iocage/iocage/issues/309) where iocage doesn't upgrade a jail?

**Comment by kdbruin** [comment] 2017-08-12 07:39
Looks like the same issue but it seems the upgrade of my jails went OK as the output of `freebsd-version` is either `11.1-RELEASE` or `11.1-RELEASE-p1` depending on when I upgraded the jail.

However, within the jail I can run `freebsd-update fetch install` and it will use the proper release.

**Comment by skarekrow** [comment] 2017-08-15 01:55
These issues aren't related, can you post a `iocage get all git` please?

**Comment by kdbruin** [comment] 2017-08-15 08:10
As requested:

    CONFIG_VERSION:8
    allow_chflags:0
    allow_mount:0
    allow_mount_devfs:0
    allow_mount_nullfs:0
    allow_mount_procfs:0
    allow_mount_tmpfs:0
    allow_mount_zfs:0
    allow_quotas:0
    allow_raw_sockets:0
    allow_set_hostname:1
    allow_socket_af:0
    allow_sysvipc:0
    available:readonly
    basejail:no
    boot:on
    bpf:off
    children_max:0
    cloned_release:11.0-RELEASE
    comment:none
    compression:lz4
    compressratio:readonly
    coredumpsize:off
    count:1
    cpuset:off
    cputime:off
    datasize:off
    dedup:off
    defaultrouter:none
    defaultrouter6:none
    depends:none
    devfs_ruleset:4
    dhcp:off
    enforce_statfs:2
    exec_clean:1
    exec_fib:0
    exec_jail_user:root
    exec_poststart:/usr/bin/true
    exec_poststop:/usr/bin/true
    exec_prestart:/usr/bin/true
    exec_prestop:/usr/bin/true
    exec_start:/bin/sh /etc/rc
    exec_stop:/bin/sh /etc/rc.shutdown
    exec_system_jail_user:0
    exec_system_user:root
    exec_timeout:60
    host_domainname:none
    host_hostname:git.home.lan
    host_hostuuid:git
    host_time:yes
    hostid:e75dfda1-5e29-11e7-9990-bc5ff4458016
    interfaces:vnet0:bridge0
    ip4:new
    ip4_addr:re0|172.16.123.54,lo1|127.0.123.54
    ip4_saddrsel:1
    ip6:new
    ip6_addr:none
    ip6_saddrsel:1
    jail_zfs:on
    jail_zfs_dataset:iocage/jails/git/data/repositories
    jail_zfs_mountpoint:/var/git/repositories
    last_started:2017-08-12 07:51:00
    login_flags:-f root
    mac_prefix:02ff60
    maxproc:off
    memorylocked:off
    memoryuse:off
    mount_devfs:1
    mount_fdescfs:1
    mount_linprocfs:0
    mount_procfs:0
    mountpoint:readonly
    msgqqueued:off
    msgqsize:off
    nmsgq:off
    notes:none
    nsemop:off
    nshm:off
    nthr:off
    openfiles:off
    origin:readonly
    owner:root
    pcpu:off
    priority:99
    pseudoterminals:off
    quota:none
    release:11.1-RELEASE
    reservation:none
    resolver:/etc/resolv.conf
    rlimits:off
    securelevel:0
    shmsize:off
    stacksize:off
    stop_timeout:30
    swapuse:off
    sync_state:none
    sync_target:none
    sync_tgt_zpool:none
    sysvmsg:new
    sysvsem:new
    sysvshm:new
    tag:git
    template:no
    type:jail
    used:readonly
    vmemoryuse:off
    vnet:off
    vnet0_mac:none
    vnet1_mac:none
    vnet2_mac:none
    vnet3_mac:none
    wallclock:off

**Comment by skarekrow** [comment] 2017-08-16 02:58
What about the `/etc/freebsd-update.conf`? From your output, it looks like you put a nonstandard mirror. In the meantime your other issue is related to https://github.com/iocage/iocage/issues/309 and I suggest to either hold out for the next release, or use `master`.

**Comment by kdbruin** [comment] 2017-08-16 06:28
I was indeed using a local cache but after I changed to using the default `/etc/freebsd-update.conf` the same message was generated.

For the #309 issue I will wait for a new release and see what needs to be done by following that issue.

**Comment by skarekrow** [comment] 2017-08-18 01:42
Sorry I can't reproduce this. I'm going to close the issue in the meantime. If I can reproduce it, I'll ofcourse reopen it 👍

**Closed as completed by skarekrow** 2017-08-18 01:42 UTC
Labels: can't reproduce
